[{assign var="payment" value=$oView->getPayment()}]
[{if "oscpaypal_acdc" == $payment->getId() || "oscpaypal_pui" == $payment->getId() || $vaultedPaymentDescription}]
    [{assign var="oConfig" value=$oViewConf->getConfig()}]
    [{assign var="PayPalSDKJS" value=$oConfig->getGlobalParameter("PayPalSDKJS")}]
    [{if !$PayPalSDKJS}]
        [{capture assign="PayPalSDKJS"}]
            [{include file="@osc_paypal/frontend/shared/layout/base_js.tpl" commitFlow=$commitFlow}]
        [{/capture}]
    [{$oConfig->setGlobalParameter("PayPalSDKJS", $PayPalSDKJS)}]
    [{/if}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{include file="@osc_paypal/frontend/flow/shipping_and_payment.tpl"}]
    [{else}]
        [{include file="@osc_paypal/frontend/wave/shipping_and_payment.tpl"}]
    [{/if}]
[{elseif "oscpaypal" == $payment->getId()}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{include file="@osc_paypal/frontend/flow/shipping_and_payment_paypal.tpl"}]
    [{else}]
        [{include file="@osc_paypal/frontend/wave/shipping_and_payment_paypal.tpl"}]
    [{/if}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]