[{assign var="config" value=$oViewConf->getPayPalCheckoutConfig()}]
[{$oViewConf->unsetPaypalSessionAndOrderId()}]
[{if $blCanBuy && !$oDetailsProduct->isNotBuyable() && $config->isActive() && $config->showPayPalProductDetailsButton()}]
    [{include file="@osc_paypal/frontend/shared/paymentbuttons.tpl" buttonId="PayPalButtonProductMain" buttonClass="paypal-button-wrapper large" aid=$oDetailsProduct->oxarticles__oxid->value}]
[{/if}]
