<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = 'Deutsch';

$aLang = [
    'charset'                                     => 'UTF-8',
    'paypal'                                      => 'PayPal',
    'OSC_PAYPAL_EDIT'                             => 'Bearbeiten',
    'OSC_PAYPAL_ACTIONS'                          => 'Aktionen',
    'OSC_PAYPAL_CAPTURE_PAYMENT'                  => 'Zahlung erfassen',
    'OSC_PAYPAL_ISSUE_REFUND'                     => 'Rückerstattung ausstellen',
    'OSC_PAYPAL_SHOW_BALANCE_AFFECTING_RECORDS'   => 'Nur die Einträge, die das Konto beeinflussen',
    'OSC_PAYPAL_REPORT_REFERENCE'                 => 'Referenz melden',
    'OSC_PAYPAL_TRANSACTION_TO_PRICE'             => 'Preis bis',
    'OSC_PAYPAL_TRANSACTION_FROM_PRICE'           => 'Preis von',
    'OSC_PAYPAL_AVAILABLE_BALANCE'                => 'Verfügbar',
    'OSC_PAYPAL_PRODUCTS'                         => 'Produkt',
    'OSC_PAYPAL_WITHHELD_BALANCE'                 => 'Zurückgehalten',
    'OSC_PAYPAL_TOTAL_BALANCE'                    => 'Gesamt',
    'OSC_PAYPAL_PRIMARY'                          => 'Primär',
    'OSC_PAYPAL_MORE'                             => 'Mehr',
    'OSC_PAYPAL_LAST_REFRESH_TIME'                => 'Letzte Aktualisierung',
    'OSC_PAYPAL_CURRENCY_CODE'                    => 'Währungscode',
    'OSC_PAYPAL_AS_OF_TIME'                       => 'seit',
    'OSC_PAYPAL_PAYMENT_INSTRUMENT_CREDIT_CARD'   => 'Kreditkarte',
    'OSC_PAYPAL_PAYMENT_INSTRUMENT_DEBIT_CARD'    => 'Debitkarte',
    'OSC_PAYPAL_TRANSACTION_STATUS_P'             => 'Ausstehend',
    'OSC_PAYPAL_TRANSACTION_STATUS_F'             => 'Teilweise erstattet',
    'OSC_PAYPAL_TRANSACTION_STATUS_D'             => 'Verweigert',
    'OSC_PAYPAL_TRANSACTION_STATUS_S'             => 'Abgeschlossen',
    'OSC_PAYPAL_TRANSACTION_STATUS_V'             => 'Erstattet',
    'OSC_PAYPAL_DISPUTE_STATUS_UNDER_REVIEW'      => 'Unter Überprüfung',
    'OSC_PAYPAL_DATE_SELECT_HELP'                 => 'Maximal 31 Tage erlaubt!',
    'OSC_PAYPAL_APPLY'                            => 'Anwenden',
    'OSC_PAYPAL_TRANSACTION_DATE_FROM'            => 'Stammen aus',
    'OSC_PAYPAL_TRANSACTION_DATE_TO'              => 'Datum bis',
    'OSC_PAYPAL_TRANSACTION_TYPE'                 => 'Transaktionstyp',
    'OSC_PAYPAL_TERMINAL_ID'                      => 'Terminal ID',
    'OSC_PAYPAL_PAYMENT_INSTRUMENT_TYPE'          => 'Instrumententyp',
    'OSC_PAYPAL_TRANSACTION_CURRENCY'             => 'Transaktionswährung',
    'OSC_PAYPAL_TRANSACTION_AMOUNT'               => 'Transaktionsbetrag',
    'OSC_PAYPAL_TRANSACTION_DATE'                 => 'Transaktionsdatum',
    'OSC_PAYPAL_STORE_ID'                         => 'Shop ID',
    'OSC_PAYPAL_ACCOUNT_ID'                       => 'Konto-ID',
    'OSC_PAYPAL_TRANSACTION_ID'                   => 'Transaktions-ID',
    'OSC_PAYPAL_REFERENCE_ID'                     => 'Referenz-ID',
    'OSC_PAYPAL_REFERENCE_ID_TYPE'                => 'Referenz-ID-Typ',
    'OSC_PAYPAL_EVENT_CODE'                       => 'Ereigniscode',
    'OSC_PAYPAL_INITIATION_DATE'                  => 'Initiationsdatum',
    'OSC_PAYPAL_UPDATED_DATE'                     => 'Aktualisierungsdatum',
    'OSC_PAYPAL_TRANSACTION_NOTE'                 => 'Hinweis',
    'OSC_PAYPAL_BANK_REFERENCE_ID'                => 'Bankreferenz-ID',
    'OSC_PAYPAL_CUSTOM_FIELD'                     => 'Benutzerdefiniertes Feld',
    'OSC_PAYPAL_CREDIT_TERM'                      => 'Kreditlaufzeit',
    'OSC_PAYPAL_INSTRUMENT_TYPE'                  => 'Instrumententyp',
    'OSC_PAYPAL_TRANSACTION_STATUS'               => 'Status',
    'OSC_PAYPAL_PAYMENT_TRACKING_ID'              => 'Zahlungsverfolgungs-ID',
    'OSC_PAYPAL_PAYMENT_METHOD_TYPE'              => 'Zahlungsmethode Typ',
    'OSC_PAYPAL_INSTRUMENT_SUB_TYPE'              => 'Untertyp',
    'OSC_PAYPAL_TRANSACTION_SUBJECT'              => 'Betreff',
    'OSC_PAYPAL_PROTECTION_ELIGIBILITY'           => 'Schutzberechtigung',
    'tbclorder_paypal'                             => 'PayPal',
    // PayPal Config
    'OSC_PAYPAL_CONFIG'                           => 'Konfiguration',
    'OSC_PAYPAL_SUBSCRIBE'                        => 'PayPal Abos',
    'OSC_PAYPAL_SUBSCRIBE_OPTIONS'                => 'PayPal Abos Optionen',
    'PAYPAL_SUBSCRIBE_MAIN'                        => 'PayPal Abos',
    'OSC_PAYPAL_BILLING_PLAN'                     => 'PayPal Abrechnungsplan',
    'OSC_PAYPAL_BILLING_PLAN_MAIN'                => 'Abrechnungsplan',
    'OSC_PAYPAL_BILLING_PLAN_NAME'                => 'Abrechnungsplan Name',
    'OSC_PAYPAL_BILLING_PLAN_TYPE'                => 'Typ',
    'OSC_PAYPAL_BILLING_PLAN_FIXED'               => 'Fix',
    'OSC_PAYPAL_BILLING_PLAN_INFINITE'            => 'Unbestimmt',
    'OSC_PAYPAL_BILLING_PLAN_DESCRIPTION'         => 'Beschreibung',
    'OSC_PAYPAL_BILLING_PLAN_DEFINITIONS'         => 'Definitionen',
    'OSC_PAYPAL_BILLING_PLAN_AUTOMATICALLY_BILL'  => 'Ausstehende Rechnungen automatisch abrechnen',
    'HELP_OSC_PAYPAL_BILLING_PLAN_AUTOMATICALLY_BILL'                              =>
        'Soll PayPal automatische Rechnungen automatisch abrechnen?',
    'OSC_PAYPAL_BILLING_PLAN_SETUP_FEE'           => 'Einrichtungsgebühr',
    'OSC_PAYPAL_BILLING_PLAN_FAILURE_ACTION'      => 'Einrichtung Fehler Aktion',
    'HELP_OSC_PAYPAL_BILLING_PLAN_FAILURE_ACTION' =>
        'Sollte bei der Einrichtung des Abos ein Fehler auftreten. Soll das Abo trotzdem angelegt
        (<b>Weiter</b>), oder der Vorgang abgebrochen (<b>Abbrechen</b>) werden?',
    'OSC_PAYPAL_BILLING_PLAN_ACTION_CONTINUE'     => 'Weiter',
    'OSC_PAYPAL_BILLING_PLAN_ACTION_CANCEL'       => 'Abbrechen',
    'OSC_PAYPAL_BILLING_PLAN_FAILURE_THRESHOLD'   => 'Wiederholungen bei Zahlungsfehler',
    'HELP_OSC_PAYPAL_BILLING_PLAN_FAILURE_THRESHOLD'                                =>
        'Wie oft soll versucht eine Zahlung durchzuführen, bis sie abgebrochen wird?',
    'OSC_PAYPAL_BILLING_PLAN_TAX'                 => 'Steuern',
    'OSC_PAYPAL_BILLING_PLAN_TAX_PERCENTAGE'      => 'Steuer Prozentual',
    'OSC_PAYPAL_BILLING_PLAN_TAX_INCLUSIVE'       => 'Steuer Inklusive',
    'OSC_PAYPAL_BILLING_PLAN_PAYPAL_ID'           => 'PayPal ID',
    'OSC_PAYPAL_BILLING_PLAN_BILLING_CYCLES'      => 'Zugewiesener Abrechnungsplan',
    'OSC_PAYPAL_BILLING_PLAN_PRICE'               => 'Preis',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY'           => 'Serie',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_DAY'       => 'täglich',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_WEEK'      => 'wöchentlich',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_SEMI_MONTH' => 'alle zwei Wochen',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_MONTH'     => 'monatlich',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_YEAR'      => 'jährlich',
    'OSC_PAYPAL_BILLING_PLAN_TENURE'              => 'Intervall',
    'OSC_PAYPAL_BILLING_PLAN_SEQUENCE'            => 'Reihenfolge',
    'OSC_PAYPAL_BILLING_PLAN_CYCLES'              => 'Wiederholungen',
    'OSC_PAYPAL_BILLING_PLAN_TOTAL_CYCLES'        => 'Summe Wiederholungen',
    'OSC_PAYPAL_BILLING_PLAN_ACTIONS'             => 'Aktionen',
    'OSC_PAYPAL_BILLING_PLAN_NO_PLANS'            => 'Keine Abrechnungspläne',
    'OSC_PAYPAL_BILLING_PLAN_ADD'                 => 'Abrechnungsplan hinzufügen',
    'OSC_PAYPAL_BILLING_PLAN_ADD_CYCLES'          => 'Wiederholung anlegen',
    'OSC_PAYPAL_BILLING_PLAN_YES'                 => 'Ja',
    'OSC_PAYPAL_BILLING_PLAN_NO'                  => 'Nein',
    'OSC_PAYPAL_BILLING_PLAN_SUBSCRIPTION_PROD'   => 'Abo Produkt',
    'OSC_PAYPAL_TRANSACTIONS'                     => 'Transaktionen',
    'OSC_PAYPAL_BALANCES'                         => 'Guthaben',
    'OSC_PAYPAL_GENERAL'                          => 'Allgemein',
    'OSC_PAYPAL_WEBHOOK_ID'                       => 'Webhook-ID',
    'OSC_PAYPAL_OPMODE'                           => 'Betriebsmodus',
    'OSC_PAYPAL_OPMODE_LIVE'                      => 'Live',
    'OSC_PAYPAL_OPMODE_SANDBOX'                   => 'Sandbox',
    'OSC_PAYPAL_CLIENT_ID'                        => 'Client-ID',
    'OSC_PAYPAL_CLIENT_SECRET'                    => 'Passwort',
    'OSC_PAYPAL_CREDENTIALS'                      => 'API-Anmeldeinformationen',
    'OSC_PAYPAL_LIVE_CREDENTIALS'                 => 'API-Anmeldeinformationen (Live)',
    'OSC_PAYPAL_SANDBOX_CREDENTIALS'              => 'API-Anmeldeinformationen (Sandbox)',
    'OSC_PAYPAL_LIVE_BUTTON_CREDENTIALS'          => 'Anmeldung Händler PayPal-Integration (Live)',
    'OSC_PAYPAL_SANDBOX_BUTTON_CREDENTIALS'       => 'Anmeldung Händler PayPal-Integration (Sandbox)',
    'OSC_PAYPAL_ERR_CONF_INVALID'                 =>
        'Ein oder mehrere Konfigurationswerte sind entweder nicht festgelegt oder falsch.
        Bitte überprüfen Sie sie noch einmal.<br>
        <b>Modul inaktiv.</b>',
    'OSC_PAYPAL_CONF_VALID'                       => 'Konfigurationswerte OK.<br><b>Modul ist aktiv</b>',
    'OSC_PAYPAL_BUTTON_PLACEMEMT_TITLE'           => 'Einstellungen für die Buttonplatzierung',
    'OSC_PAYPAL_PRODUCT_DETAILS_BUTTON_PLACEMENT' => 'Produktdetailseite',
    'OSC_PAYPAL_BASKET_BUTTON_PLACEMENT'          => 'Warenkorb',
    'OSC_PAYPAL_CHECKOUT_PLACEMENT'               => 'Bezahlseite (Checkout)',
    'OSC_PAYPAL_EXPRESS_LOGIN_TITLE'              => 'Login mit PayPal',
    'OSC_PAYPAL_LOGIN_WITH_PAYPAL_EMAIL'          => 'Im Shop beim Kauf automatisch einloggen',
    'HELP_OSC_PAYPAL_EXPRESS_LOGIN'               => 'Wenn die Shop-Kundenkonto-EMail-Adresse gleich der PayPal-EMail-Adresse ist,
        besteht die Möglichkeit, sich durch ein Login bei PayPal auch automatisch im Shop anzumelden. Möglicherweise ist dieses Verhalten nicht im
        Sicherheitsinteresse Ihrer Kunden',

    'HELP_OSC_PAYPAL_BUTTON_PLACEMEMT'            => 'Schalten Sie die Anzeige der PayPal-Schaltflächen um',
    'HELP_OSC_PAYPAL_CREDENTIALS'                 =>
        'Wenn Sie die API-Anmeldeinformationen (Client-ID, Client Passwort, Webhook-ID) bereits vorliegen haben, können Sie sie direkt eingeben.<br>
        Sollten Sie noch keine API-Daten haben und die Eingafelder noch leer sein, können Sie auch den eingeblendeten
        Button für eine komfortable Verknüpfung nutzen.',
    'HELP_OSC_PAYPAL_CLIENT_ID'                   => 'Client-ID des Live-Account für Live-Modus',
    'HELP_OSC_PAYPAL_CLIENT_SECRET'               => 'Secret des Live-Account für Live-Modus',
    'HELP_OSC_PAYPAL_SANDBOX_CLIENT_ID'           => 'Client-ID des Sandbox-Account für Sandbox-Modus',
    'HELP_OSC_PAYPAL_SANDBOX_CLIENT_SECRET'       => 'Secret des Sandbox-Account für Sandbox-Modus. Bitte geben Sie das Passwort zweimal ein.',
    'HELP_OSC_PAYPAL_SANDBOX_WEBHOOK_ID'          =>
        'Die ID des Sandboox-Webhooks, wie in Ihrem Developer Portal-Konto konfiguriert',
    'HELP_OSC_PAYPAL_OPMODE'                      =>
        'Verwenden Sie Sandbox (Test), um PayPal zu konfigurieren und zu testen. Wenn Sie bereit sind,
        echte Transaktionen zu empfangen, wechseln Sie zu Produktion (live).',
    'HELP_OSC_PAYPAL_WEBHOOK_ID'                  =>
        'Die ID des Webhooks, wie in Ihrem Developer Portal-Konto konfiguriert',

    // PayPal ORDER
    'OSC_PAYPAL_AMOUNT'                           => 'Betrag',
    'OSC_PAYPAL_SHOP_PAYMENT_STATUS'              => 'Shop-Zahlungsstatus',
    'OSC_PAYPAL_ORDER_PRICE'                      => 'Bestellpreis gesamt',
    'OSC_PAYPAL_ORDER_PRODUCTS'                   => 'Bestellte Artikel',
    'OSC_PAYPAL_CAPTURED'                         => 'Eingezogen',
    'OSC_PAYPAL_REFUNDED'                         => 'Erstattet',
    'OSC_PAYPAL_CAPTURED_NET'                     => 'Resultierender Zahlungsbetrag',
    'OSC_PAYPAL_CAPTURED_AMOUNT'                  => 'Eingezogener Betrag',
    'OSC_PAYPAL_REFUNDED_AMOUNT'                  => 'Erstatteter Betrag',
    'OSC_PAYPAL_VOIDED_AMOUNT'                    => 'Stornierter Betrag',
    'OSC_PAYPAL_MONEY_CAPTURE'                    => 'Geldeinzug',
    'OSC_PAYPAL_MONEY_REFUND'                     => 'Gelderstattung',
    'OSC_PAYPAL_CAPTURE'                          => 'Einziehen',
    'OSC_PAYPAL_REFUND'                           => 'Erstatten',
    'OSC_PAYPAL_DETAILS'                          => 'Details',
    'OSC_PAYPAL_AUTHORIZATION'                    => 'Autorisierung',
    'OSC_PAYPAL_CANCEL_AUTHORIZATION'             => 'Stornieren',
    'OSC_PAYPAL_PAYMENT_HISTORY'                  => 'PayPal-Historie',
    'OSC_PAYPAL_HISTORY_DATE'                     => 'Datum',
    'OSC_PAYPAL_HISTORY_ACTION'                   => 'Aktion',
    'OSC_PAYPAL_HISTORY_PAYPAL_STATUS'            => 'PayPal-Status',
    'OSC_PAYPAL_HISTORY_PAYPAL_STATUS_HELP'       =>
        'Von PayPal zurückgegebener Zahlungsstatus. Für mehr Details siehe (nur Englisch):
        <a href="https://www.paypal.com/webapps/helpcenter/article/?articleID=94021&m=SRE" target="_blank">
            PayPal Zahlungsstatus
        </a>',
    'OSC_PAYPAL_HISTORY_COMMENT'                  => 'Kommentar',
    'OSC_PAYPAL_HISTORY_NOTICE'                   => 'Hinweis',
    'OSC_PAYPAL_HISTORY_NOTICE_TEXT'              => 'Im Fehlerfall siehe "Details" für mehr Informationen',
    'OSC_PAYPAL_MONEY_ACTION_FULL'                => 'vollständig',
    'OSC_PAYPAL_MONEY_ACTION_PARTIAL'             => 'teilweise',
    'OSC_PAYPAL_LIST_STATUS_ALL'                  => 'Alle',
    'OSC_PAYPAL_STATUS_APPROVED'                  => 'genehmigt',
    'OSC_PAYPAL_STATUS_COMPLETED'                 => 'abgeschlossen',
    'OSC_PAYPAL_STATUS_DECLINED'                  => 'abgelehnt',
    'OSC_PAYPAL_STATUS_PARTIALLY_REFUNDED'        => 'Teilweise erstattet',
    'OSC_PAYPAL_STATUS_PENDING'                   => 'steht aus',
    'OSC_PAYPAL_STATUS_REFUNDED'                  => 'Erstattet',
    'OSC_PAYPAL_PAYMENT_METHOD'                   => 'Zahlungsart',
    'OSC_PAYPAL_CLOSE'                            => 'Schließen',
    'OSC_PAYPAL_COMMENT'                          => 'Kommentar',
    'OSC_PAYPAL_RESPONSE_FROM_PAYPAL'             => 'Fehlermeldung von PayPal: ',
    'OSC_PAYPAL_AUTHORIZATIONID'                  => 'Autorisierungs-ID',
    'OSC_PAYPAL_TRANSACTIONID'                    => 'Transaktions-ID',
    'OSC_PAYPAL_REFUND_AMOUNT'                    => 'Rückerstattungsbetrag',
    'OSC_PAYPAL_INVOICE_ID'                       => 'Rechnungs-Nr',
    'OSC_PAYPAL_NOTE_TO_BUYER'                    => 'Hinweis für Käufer',
    'OSC_PAYPAL_REFUND_ALL'                       => 'Alle erstatten',
    'OSC_PAYPAL_SUBSCRIPTION'                     => 'Abonnement',
    'OSC_PAYPAL_SUBSCRIPTION_ID'                  => 'Abonnement-ID',
    'OSC_PAYPAL_SUBSCRIPTION_PLAN_ID'             => 'Plan-ID',
    'OSC_PAYPAL_SUBSCRIPTION_START_TIME'          => 'Startzeit',
    'OSC_PAYPAL_SUBSCRIPTION_QUANTITY'            => 'Menge',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS'              => 'Status',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_CHANGE_NOTE'  => 'Statusänderungsnotiz',
    'OSC_PAYPAL_SUBSCRIPTION_CREATE_TIME'         => 'Erstellt',
    'OSC_PAYPAL_SUBSCRIPTION_UPDATE_TIME'         => 'Aktualisiert',
    'OSC_PAYPAL_SUBSCRIBER_PAYER_ID'              => 'Zahler-ID',
    'OSC_PAYPAL_FIRST_NAME'                       => 'Vorname',
    'OSC_PAYPAL_LAST_NAME'                        => 'Nachname',
    'OSC_PAYPAL_FULL_NAME'                        => 'Vollständiger Name',
    'OSC_PAYPAL_EMAIL'                            => 'Email',
    'OSC_PAYPAL_ADDRESS_LINE_1'                   => 'Adresse Zeile 1',
    'OSC_PAYPAL_ADDRESS_LINE_2'                   => 'Adresse Zeile 2',
    'OSC_PAYPAL_ADDRESS_LINE_3'                   => 'Adresse Zeile 3',
    'OSC_PAYPAL_ADMIN_AREA_1'                     => 'Provinz, Bundesland oder ISO-Unterteilung',
    'OSC_PAYPAL_ADMIN_AREA_2'                     => 'Stadt',
    'OSC_PAYPAL_ADMIN_AREA_3'                     => 'Ortsteil, Vorort, Bezirk',
    'OSC_PAYPAL_ADMIN_AREA_4'                     => 'Nachbarschaft, Gemeinde',
    'OSC_PAYPAL_POSTAL_CODE'                      => 'Postleitzahl',
    'OSC_PAYPAL_COUNTRY_CODE'                     => 'Ländercode',
    'OSC_PAYPAL_SUBSCRIPTION_NEXT_BILLING_TIME'   => 'Nächste Abrechnung',
    'OSC_PAYPAL_SUBSCRIPTION_NEXT_PAYMENT_TIME'   => 'Nächste Zahlung',
    'OSC_PAYPAL_SUBSCRIPTION_FINAL_PAYMENT'       => 'Restzahlung',
    'OSC_PAYPAL_SUBSCRIPTION_FAILED_PAYMENT_COUNT'                                  => 'Fehlgeschlagene Zahlungen',
    'OSC_PAYPAL_SUBSCRIPTION_LAST_FAILED_PAYMENT' => 'Letzte fehlgeschlagene Zahlung',
    'OSC_PAYPAL_SUBSCRIPTION_TOTAL_PAID_AMOUNT'   => 'Gesamtbetrag bezahlt',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_UPDATE_TIME'  => 'Status aktualisiert',
    'OSC_PAYPAL_SUBSCRIBER'                       => 'Abonnent',
    'OSC_PAYPAL_SHIPPING'                         => 'Versand',
    'OSC_PAYPAL_BILLING'                          => 'Abrechnung',
    'OSC_PAYPAL_SUBSCRIPTIONS'                    => 'Abonnements',
    'OSC_PAYPAL_SUBSCRIPTIONS_SHORT'              => 'PP Abos',
    'OSC_PAYPAL_SUBSCRIPTION_OUTSTANDING_BALANCE' => 'Ausstehender Saldo',
    'OSC_PAYPAL_SUBSCRIPTION_LAST_PAYMENT'        => 'Letzter Zahlungsbetrag',
    'OSC_PAYPAL_SUBSCRIPTION_LAST_PAYMENT_TIME'   => 'Letzte Zahlung',
    'OSC_PAYPAL_SUBSCRIPTION_FAILED_PAYMENT_REASON' => 'Grund',
    'OSC_PAYPAL_SUBSCRIPTION_FAILED_PAYMENT_RETRY_TIME'                             => 'Wiederholen',
    'OSC_PAYPAL_TIME'                             => 'Zeit',
    'OSC_PAYPAL_TENURE_TYPE'                      => 'Abo-Zeitart',
    'OSC_PAYPAL_TENURE_TYPE_TRIAL'                => 'Probeabo',
    'OSC_PAYPAL_TENURE_TYPE_REGULAR'              => 'Normal',
    'OSC_PAYPAL_SEQUENCE'                         => 'Sequenz',
    'OSC_PAYPAL_CYCLES_COMPLETED'                 => 'Zyklen abgeschlossen',
    'OSC_PAYPAL_CURRENT_PRICING_SCHEME_VERSION'   => 'Version des Preisschemas',
    'OSC_PAYPAL_TOTAL_CYCLES'                     => 'Gesamtzyklen',
    'OSC_PAYPAL_CYCLES_REMAINING'                 => 'verbleibende Zyklen',
    'OSC_PAYPAL_SUBSCRIPTION_STARTS'              => 'Beginn',
    'OSC_PAYPAL_SUBSCRIPTION_EMAIL'               => 'Email',
    'OSC_PAYPAL_SUBSCRIPTION_UPDATED'             => 'Aktualisiert',
    'OSC_PAYPAL_SUBSCRIPTION_CREATED'             => 'Erstellt',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_UPDATED'      => 'Status aktualisiert',
    'OSC_PAYPAL_STATUS_CREATED'                   => 'Erstellt',
    'OSC_PAYPAL_STATUS_INACTIVE'                  => 'Inaktiv',
    'OSC_PAYPAL_STATUS_ACTIVE'                    => 'Aktiv',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_APPROVAL_PENDING'                               => 'Genehmigung ausstehend',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_APPROVED'     => 'Genehmigt',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_ACTIVE'       => 'Aktiv',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_SUSPENDED'    => 'Schwebend',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_CANCELLED'    => 'Abgebrochen',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_EXPIRED'      => 'Abgelaufen',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_ID'      => 'Transaktions-ID',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_STATUS'  => 'Transaktionsstatus',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_GROSS_AMOUNT'                              => 'Bruttobetrag',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_NET_AMOUNT'                                => 'Nettobetrag',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_FEE_AMOUNT'                                => 'Gebührenbetrag',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_DATE'    => 'Datum',
    'OSC_PAYPAL_FROM'                             => 'Von',
    'OSC_PAYPAL_TO'                               => 'Bis',
    'OSC_PAYPAL_BACK'                             => 'Zurück',
    'OSC_PAYPAL_NOTE'                             => 'Bemerkung',
    'OSC_PAYPAL_CAPTURE_OUTSTANDING_FEES'         => 'Erfassen Sie ausstehende Gebühren',
    'OSC_PAYPAL_DISPUTES'                         => 'Streitigkeiten',
    'OSC_PAYPAL_DISPUTE_START_TIME'               => 'Startzeit',
    'OSC_PAYPAL_DISPUTE_TRANSACTION_ID'           => 'Transaktions-ID',
    'OSC_PAYPAL_DISPUTE_STATE'                    => 'Status',
    'OSC_PAYPAL_DISPUTE_STATUS_REQUIRED_ACTION'   => 'Aktion erforderlich',
    'OSC_PAYPAL_DISPUTE_STATUS_REQUIRED_OTHER_PARTY_ACTION'                         =>
        'Aktion anderer Partei erforderlich',
    'OSC_PAYPAL_DISPUTE_STATUS_UNDER_PAYPAL_REVIEW'                                 => 'Unter PayPal-Überprüfung',
    'OSC_PAYPAL_DISPUTE_STATUS_RESOLVED'          => 'Gelöst',
    'OSC_PAYPAL_DISPUTE_STATUS_OPEN_INQUIRIES'    => 'Öffnen',
    'OSC_PAYPAL_DISPUTE_STATUS_APPEALABLE'        => 'Anfechtbar',
    'OSC_PAYPAL_DISPUTE_STATUS_WAITING_FOR_BUYER_RESPONSE'                          =>
        'Warten auf Antwort des Käufers',
    'OSC_PAYPAL_DISPUTE_STATUS_WAITING_FOR_SELLER_RESPONSE'                         =>
        'Warten auf Antwort des Verkäufers',
    'OSC_PAYPAL_DISPUTE_ID'                       => 'Streitstatus ID',
    'OSC_PAYPAL_DISPUTE_STATUS'                   => 'Status',
    'OSC_PAYPAL_DISPUTE_AMOUNT'                   => 'Betrag',
    'OSC_PAYPAL_DISPUTE_CREATE_TIME'              => 'Zeit erstellen',
    'OSC_PAYPAL_DISPUTE_UPDATE_TIME'              => 'Aktualisierungszeit',
    'OSC_PAYPAL_DISPUTE_REASON'                   => 'Grund',
    'OSC_PAYPAL_DISPUTE_REASON_MERCHANDISE_OR_SERVICE_NOT_RECEIVED'                 =>
        'Ware oder Dienstleistung nicht erhalten',
    'OSC_PAYPAL_DISPUTE_REASON_MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED'             =>
        'Ware oder Dienstleistung nicht wie beschrieben',
    'OSC_PAYPAL_DISPUTE_REASON_UNAUTHORISED'      => 'Nicht autorisiert',
    'OSC_PAYPAL_DISPUTE_REASON_CREDIT_NOT_PROCESSED'                                => 'Gutschrift nicht verarbeitet',
    'OSC_PAYPAL_DISPUTE_REASON_CREDIT_DUPLICATE_TRANSACTION'                        =>
        'Doppelte Transaktion gutschreiben',
    'OSC_PAYPAL_DISPUTE_REASON_INCORRECT_AMOUNT'                                    => 'Falscher Betrag',
    'OSC_PAYPAL_DISPUTE_REASON_PAYMENT_BY_OTHER_MEANS'                              => 'Zahlung auf andere Weise',
    'OSC_PAYPAL_DISPUTE_REASON_CANCELED_RECURRING_BILLING'                          =>
        'Abgebrochene wiederkehrende Abrechnung abgebrochen',
    'OSC_PAYPAL_DISPUTE_REASON_PROBLEM_WITH_REMITTANCE'                             => 'Problem mit Überweisung',
    'OSC_PAYPAL_DISPUTE_REASON_OTHER'             => 'Andere',
    'OSC_PAYPAL_REASON'                           => 'Grund',
    'OSC_PAYPAL_STATUS'                           => 'Status',
    'OSC_PAYPAL_DISPUTE_INVOICE_ID'               => 'Rechnungsnummer',
    'OSC_PAYPAL_DISPUTE_OFFER_TYPE'               => 'Angebotstyp',
    'OSC_PAYPAL_DISPUTE_NOTE'                     => 'Hinweis',
    'OSC_PAYPAL_DISPUTE_OFFER_AMOUNT'             => 'Angebots Betrag',
    'OSC_PAYPAL_SUBSCRIPTION_BILLING'             => 'Abrechnung',
    'OSC_PAYPAL_SEND'                             => 'Senden',
    'OSC_PAYPAL_DISPUTE_REFUND'                   => 'Rückerstattung',
    'OSC_PAYPAL_DISPUTE_REFUND_WITH_RETURN'       => 'Rückerstattung mit Rückgabe',
    'OSC_PAYPAL_DISPUTE_REFUND_WITH_REPLACEMENT'  => 'Rückerstattung mit Ersatz',
    'OSC_PAYPAL_DISPUTE_REPLACEMENT_WITHOUT_REFUND'                                 =>
        'Ersatz ohne Rückerstattung',
    'OSC_PAYPAL_SUBSCRITION_PART_NOTE'            =>
        'Das ist eine Teillieferung eines Abos. Die Informationen zu diesem Abo finden Sie in der Hauptbestellung Nr.',
    // Errors
    'OSC_PAYPAL_ERROR_NOT_PAID_WITH_PAYPAL'       => 'Diese Bestellung wurde nicht mit PayPal bezahlt',
    'OSC_PAYPAL_ERROR_INVALID_RESOURCE_ID'        =>
        'Die Bestellung konnte nicht in Ihrem PayPal-Account gefunden werden.',
    'OSC_PAYPAL_ERROR_DUPLICATE_INVOICE_ID'       =>
        'Die Rechnungsnummer ist bereits vergeben, bitte wählen Sie eine Andere.',
    'OSC_PAYPAL_MESSAGES'                         => 'Nachrichten',
    'OSC_PAYPAL_SEND_MESSAGES'                    => 'Nachrichten senden',
    'OSC_PAYPAL_MAKE_OFFER'                       => 'Angebot machen',
    'OSC_PAYPAL_ESCALATE'                         => 'Eskalieren',
    'OSC_PAYPAL_HISTORY'                          => 'Geschichte',
    'OSC_PAYPAL_RESOLVED_BUYER_FAVOUR'            => 'Beschlossen zu Gunsten des Käufers',
    'OSC_PAYPAL_RESOLVED_SELLER_FAVOUR'           => 'Beschlossen zu Gunsten des Verkäufers',
    'OSC_PAYPAL_PRODUCT_ID'                       => 'Produkt-ID',
    'OSC_PAYPAL_PRODUCT_NAME'                     => 'Produktname',
    'HELP_OSC_PAYPAL_PRODUCT_NAME'                =>
        'Der Produktname wird, für die bessere Identifizierung im PayPal-Konto, mit an PayPal übergeben.',
    'OSC_PAYPAL_PRODUCT_DESCRIPTION'              => 'Beschreibung',
    'HELP_OSC_PAYPAL_PRODUCT_DESCRIPTION'         =>
        'Die Beschreibung wird, für die bessere Identifizierung im PayPal-Konto, mit an PayPal übergeben.',
    'OSC_PAYPAL_PRODUCT_TYPE'                     => 'Produkt-Typ',
    'OSC_PAYPAL_PRODUCT_TYPE_CATEGORY'            => 'Typ-Kategorie',
    'OSC_PAYPAL_PRODUCT_URL'                      => 'URL',
    'OSC_PAYPAL_PRODUCT_IMAGE'                    => 'Bild',
    'HELP_OSC_PAYPAL_PRODUCT_IMAGE'               =>
        'Dieses Bild wird, für die bessere Identifizierung im PayPal-Konto, mit an PayPal übergeben.',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_SHIPMENT_NOT_ARRIVED'                        =>
        'Die Sendung ist nicht angekommen',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_FRAUDULENT_SELLER'                           => 'Betrügerischer Verkäufer',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_FAILED_NEGOTIATION'                          => 'Gescheiterte Verhandlung',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_INCONCLUSIVE_NEGOTIATION'                    => 'Verhandlung ohne Ergebnis',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_REFUND_NOT_RECEIVED'                         =>
        'Rückerstattung nicht erhalten',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_REFUND_AMOUNT_IS_DIFFERENT'                  =>
        'Rückerstattungsbetrag ist unterschiedlich',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_TRACKING_ID_INVALID'                         => 'Tracking-ID ist ungültig',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_OTHER'    => 'Andere',
    'OSC_PAYPAL_EVIDENCE'                         => 'Beweise',
    'OSC_PAYPAL_PROVIDE_EVIDENCE'                 => 'Beweise liefern',
    'OSC_PAYPAL_UPLOAD_FILE'                      => 'Datei hochladen',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_FULFILLMENT'                                  => 'Nachweis der Erfüllung',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_REFUND'    => 'Nachweis der Rückerstattung',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_DELIVERY_SIGNATURE'                           => 'Zustellnachweis-Signatur',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_RECEIPT_COPY'                                 => 'Kopie des Empfangsnachweises',
    'OSC_PAYPAL_EVIDENCE_TYPE_RETURN_POLICY'      => 'Rückkehr-Richtlinie',
    'OSC_PAYPAL_EVIDENCE_TYPE_BILLING_AGREEMENT'  => 'Vereinbarung zur Rechnungsstellung',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_RESHIPMENT'                                   => 'Nachweis der Rücksendung',
    'OSC_PAYPAL_EVIDENCE_TYPE_ITEM_DESCRIPTION'   => 'Objekt Beschreibung',
    'OSC_PAYPAL_EVIDENCE_TYPE_POLICE_REPORT'      => 'Polizeibericht',
    'OSC_PAYPAL_EVIDENCE_TYPE_AFFIDAVIT'          => 'Eidesstattliche Erklärung',
    'OSC_PAYPAL_EVIDENCE_TYPE_PAID_WITH_OTHER_METHOD'                                => 'Bezahlt mit anderer Methode',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_CONTRACT'   => 'Kopie des Vertrags',
    'OSC_PAYPAL_EVIDENCE_TYPE_TERMINAL_ATM_RECEIPT'                                  => 'Terminal Atm Quittung',
    'OSC_PAYPAL_EVIDENCE_TYPE_PRICE_DIFFERENCE_REASON'                               => 'Grund der Preisdifferenz',
    'OSC_PAYPAL_EVIDENCE_TYPE_SOURCE_CONVERSION_RATE'                                => 'Quellenumwandlungsrate',
    'OSC_PAYPAL_EVIDENCE_TYPE_BANK_STATEMENT'     => 'Kontoauszug',
    'OSC_PAYPAL_EVIDENCE_TYPE_CREDIT_DUE_REASON'  => 'Grund für die Kreditwürdigkeit',
    'OSC_PAYPAL_EVIDENCE_TYPE_REQUEST_CREDIT_RECEIPT'                                => 'Kreditquittung anfordern',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_RETURN'    => 'Nachweis der Rückkehr',
    'OSC_PAYPAL_EVIDENCE_TYPE_CREATE'             => 'erstellen',
    'OSC_PAYPAL_EVIDENCE_TYPE_CHANGE_REASON'      => 'Grund der Änderung',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_REFUND_OUTSIDE_PAYPAL'                        =>
        'Nachweis der Rückerstattung außerhalb von PayPal',
    'OSC_PAYPAL_EVIDENCE_TYPE_RECEIPT_OF_MERCHANDISE'                                => 'Empfang von Waren',
    'OSC_PAYPAL_EVIDENCE_TYPE_CUSTOMS_DOCUMENT'   => 'Zolldokument',
    'OSC_PAYPAL_EVIDENCE_TYPE_CUSTOMS_FEE_RECEIPT'                                   => 'Quittung der Zollgebühren',
    'OSC_PAYPAL_EVIDENCE_TYPE_INFORMATION_ON_RESOLUTION'                             => 'Informationen zur Resolution',
    'OSC_PAYPAL_EVIDENCE_TYPE_ADDITIONAL_INFORMATION_OF_ITEM'                        =>
        'Zusätzliche Informationen zum Artikel',
    'OSC_PAYPAL_EVIDENCE_TYPE_DETAILS_OF_PURCHASE'                                   => 'Details zum Kauf',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_SIGNIFICANT_DIFFERENCE'                       =>
        'Nachweis eines signifikanten Unterschieds',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_SOFTWARE_OR_SERVICE_NOT_AS_DESCRIBED'         =>
        'Nachweis von Software oder Dienstleistung nicht wie beschrieben',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_CONFISCATION'                                 => 'Nachweis der Beschlagnahme',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_DAMAGE'    => 'Nachweis eines Schadens',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_LAW_ENFORCEMENT_AGENCY_REPORT'                 =>
        'Kopie des Berichts der Strafverfolgungsbehörde',
    'OSC_PAYPAL_EVIDENCE_TYPE_ADDITIONAL_PROOF_OF_SHIPMENT'                          => 'Zusätzlicher Versandnachweis',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_DENIAL_BY_CARRIER'                            =>
        'Nachweis der Ablehnung durch den Beförderer',
    'OSC_PAYPAL_EVIDENCE_TYPE_THIRDPARTY_PROOF_FOR_DAMAGE_OR_SIGNIFICANT_DIFFERENCE' =>
        'Drittpartei-Beweis für Schäden oder signifikante Unterschiede',
    'OSC_PAYPAL_EVIDENCE_TYPE_VALID_SUPPORTING_DOCUMENT'                             =>
        'Gültiges unterstützendes Dokument',
    'OSC_PAYPAL_EVIDENCE_TYPE_LEGIBLE_SUPPORTING_DOCUMENT'                           => 'Lesbares Begleitdokument',
    'OSC_PAYPAL_EVIDENCE_TYPE_RETURN_TRACKING_INFORMATION'                           =>
        'Informationen zur Rücklaufverfolgung',
    'OSC_PAYPAL_EVIDENCE_TYPE_DELIVERY_RECEIPT'   => 'Zustellschein',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_INSTORE_RECEIPT'                              =>
        'Nachweis des Instore-Empfangs',
    'OSC_PAYPAL_EVIDENCE_TYPE_ADDITIONAL_TRACKING_INFORMATION'                       =>
        'Zusätzliche Tracking-Informationen',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_SHIPMENT_POSTAGE'                             => 'Versandnachweis Porto',
    'OSC_PAYPAL_EVIDENCE_TYPE_ONLINE_TRACKING_INFORMATION'                           =>
        'Informationen zur Online-Verfolgung',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_INSTORE_REFUND'                               =>
        'Nachweis der Instore-Rückerstattung',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_FOR_SOFTWARE_OR_SERVICE_DELIVERED'               =>
        'Nachweis für gelieferte Software oder Dienstleistung',
    'OSC_PAYPAL_EVIDENCE_TYPE_RETURN_ADDRESS_FOR_SHIPPING'                           =>
        'Rücksendeadresse für den Versand',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_THE_EPARCEL_MANIFEST'                          => 'Kopie des Paketmanifests',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_SHIPPING_MANIFEST'                             => 'Kopie des Versandmanifests',
    'OSC_PAYPAL_EVIDENCE_TYPE_APPEAL_AFFIDAVIT'                                      =>
        'Berufung Eidesstattliche Erklärung',
    'OSC_PAYPAL_EVIDENCE_TYPE_RECEIPT_OF_REPLACEMENT'                                => 'Eingang des Ersatzes',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_DRIVERS_LICENSE'                               => 'Kopie des Führerscheins',
    'OSC_PAYPAL_EVIDENCE_TYPE_ACCOUNT_CHANGE_INFORMATION'                            => 'Konto-Änderungsinformationen',
    'OSC_PAYPAL_EVIDENCE_TYPE_DELIVERY_ADDRESS'                                      => 'Lieferadresse',
    'OSC_PAYPAL_EVIDENCE_TYPE_CONFIRMATION_OF_RESOLUTION'                            => 'Bestätigung der Resolution',
    'OSC_PAYPAL_EVIDENCE_TYPE_MERCHANT_RESPONSE'                                     => 'Antwort des Händlers',
    'OSC_PAYPAL_EVIDENCE_TYPE_PERMISSION_DESCRIPTION'                                => 'Beschreibung der Erlaubnis',
    'OSC_PAYPAL_EVIDENCE_TYPE_STATUS_OF_MERCHANDISE'                                 => 'Status der Ware',
    'OSC_PAYPAL_EVIDENCE_TYPE_LOST_CARD_DETAILS'                                     => 'Details zur verlorenen Karte',
    'OSC_PAYPAL_EVIDENCE_TYPE_LAST_VALID_TRANSACTION_DETAILS'                        =>
        'Details zur letzten gültigen Transaktion',
    'OSC_PAYPAL_EVIDENCE_TYPE_OTHER'              => 'Andere',
    'OSC_PAYPAL_EVIDENCE_TYPE'                    => 'Art der Beweise',
    'OSC_PAYPAL_EVIDENCE_DOCUMENT'                => 'Dokument',
    'OSC_PAYPAL_FILTER'                           => 'Filter',
    'OSC_PAYPAL_CREATED'                          => 'erstellt',
    'OSC_PAYPAL_ME'                               => 'Ich',
    'OSC_PAYPAL_COPY'                             => 'Kopieren',

    'TOOLTIPS_OSC_PAYPAL_EDITSUBSCRIPTION'        => 'Abrechnungsplan editieren',
    'TOOLTIPS_OSC_PAYPAL_DEACTIVATESUBSCRIPTION'  => 'Abrechnungsplan deaktivieren',

    // PSPAYPAL-491 -->
    'OSC_PAYPAL_BANNER_CREDENTIALS'                => 'Banner-Einstellungen',
    'OSC_PAYPAL_BANNER_INFOTEXT'                   => 'Bieten Sie Ihren Kunden PayPal Ratenzahlung mit 0% effektiven Jahreszins an. <a href="https://www.paypal.com/de/webapps/mpp/installments" target="_blank">Erfahren Sie hier mehr</a>.',
    'OSC_PAYPAL_BANNER_SHOW_ALL'                   => 'Ratenzahlung-Banner aktivieren',
    'HELP_OSC_PAYPAL_BANNER_SHOP_MODULE_SHOW_ALL'  => 'Aktivieren Sie diese Einstellung, um die Bannerfunktion zuzulassen.',
    'OSC_PAYPAL_BANNER_STARTPAGE'                   => 'Ratenzahlung-Banner auf Startseite anzeigen',
    'OSC_PAYPAL_BANNER_STARTPAGESELECTOR'           => 'CSS-Selektor der Startseite hinter dem das Banner angezeigt wird.',
    'HELP_OSC_PAYPAL_BANNER_STARTPAGESELECTOR'      => 'Standardwerte für die Themes "Flow" und "Wave": \'#wrapper .row\' bzw. \'#wrapper .container\'. Nach diesen CSS-Selektoren wird das Banner angezeigt.',
    'OSC_PAYPAL_BANNER_CATEGORYPAGE'                => 'Ratenzahlung-Banner auf Kategorieseiten anzeigen',
    'OSC_PAYPAL_BANNER_CATEGORYPAGESELECTOR'        => 'CSS-Selektor der Kategorieseiten hinter dem das Banner angezeigt wird.',
    'HELP_OSC_PAYPAL_BANNER_CATEGORYPAGESELECTOR'   => 'Standardwerte für die Themes "Flow" und "Wave": \'.page-header\' bzw. \'.page-header\'. Nach diesen CSS-Selektoren wird das Banner angezeigt.',
    'OSC_PAYPAL_BANNER_SEARCHRESULTSPAGE'           => 'Ratenzahlung-Banner bei Suchergebnissen anzeigen',
    'OSC_PAYPAL_BANNER_SEARCHRESULTSPAGESELECTOR'   => 'CSS-Selektor der Suchergebnisse hinter dem das Banner angezeigt wird.',
    'HELP_OSC_PAYPAL_BANNER_SEARCHRESULTSPAGESELECTOR' => 'Standardwerte für die Themes "Flow" und "Wave": \'#content .page-header .clearfix\' bzw. \'.page-header\'. Nach diesen CSS-Selektoren wird das Banner angezeigt.',
    'OSC_PAYPAL_BANNER_DETAILSPAGE'                 => 'Ratenzahlung-Banner auf Detailseiten anzeigen',
    'OSC_PAYPAL_BANNER_DETAILSPAGESELECTOR'         => 'CSS-Selektor der Detailseiten hinter dem das Banner angezeigt wird.',
    'HELP_OSC_PAYPAL_BANNER_DETAILSPAGESELECTOR'    => 'Standardwerte für die Themes "Flow" und "Wave": \'.detailsParams\' bzw. \'#detailsItemsPager\'. Nach diesen CSS-Selektoren wird das Banner angezeigt.',
    'OSC_PAYPAL_BANNER_CHECKOUTPAGE'                => 'Ratenzahlung-Banner im Warenkorb anzeigen',
    'OSC_PAYPAL_BANNER_CARTPAGESELECTOR'            => 'CSS-Selektor der Warenkorbübersicht (Bestellschritt 1) hinter dem das Banner angezeigt wird.',
    'HELP_OSC_PAYPAL_BANNER_CARTPAGESELECTOR'       => 'Standardwerte für die Themes "Flow" und "Wave": \'.cart-buttons\' und \'.cart-buttons\'. Nach diesen CSS-Selektoren wird das Banner angezeigt.',
    'OSC_PAYPAL_BANNER_PAYMENTPAGESELECTOR'         => 'CSS-Selektor der Seite "Versand & Zahlungsart" (Bestellschritt 3) hinter dem das Banner angezeigt wird.',
    'HELP_OSC_PAYPAL_BANNER_PAYMENTPAGESELECTOR'    => 'Standardwerte für die Themes "Flow" und "Wave": \'.checkoutSteps ~ .spacer\' bzw. \'.checkout-steps\'. Nach diesen CSS-Selektoren wird das Banner angezeigt.',
    'OSC_PAYPAL_BANNER_COLORSCHEME'                 => 'Farbe des Ratenzahlung-Banners auswählen',
    'OSC_PAYPAL_BANNER_COLORSCHEMEBLUE'             => 'blau',
    'OSC_PAYPAL_BANNER_COLORSCHEMEBLACK'            => 'schwarz',
    'OSC_PAYPAL_BANNER_COLORSCHEMEWHITE'            => 'weiß',
    'OSC_PAYPAL_BANNER_COLORSCHEMEWHITENOBORDER'    => 'weiß, ohne Rand',
    // <-- PSPAYPAL-491

    'OSC_PAYPAL_SUBSCRITION_PART_ARTICLE_TITLE'   => '%s (Teillieferung Nr. %s von %s)',
];
