# {{ $ids := "osc_paypal" }}ids: {{ $ids }}
# {{ $org := "oxid-solution-catalysts" }}organisation: {{ $org }}
# {{ $name := "paypal-module" }}name: {{ $name }}
# {{ $repo := "OXID-eSales/paypal-module" }}repo: {{ $repo }}
install:
  cache:
    prepared_shop: false
  method: 'script'
  script: '.github/oxid-esales/install.sh'
  add_service: 'node'
  git:
    repository: '{{ $repo }}'
    ref: &ref '{{ .Github.RefName }}'
    shop_url: 'https://github.com/OXID-eSales/paypal-module.git'
    shop_ref: *ref
  container:
    options: '-e ESHOP_BOOTSTRAP_PATH=vendor/oxid-esales/oxideshop-ce/source/bootstrap.php -e THEME_ID=apex'
  composer:
    root_url: ''
    transform: |
      {
          "minimum-stability": "dev",
          "require-dev": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}"
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:theme:activate apex
    cp tests/.env.dist tests/.env
    mkdir -p /var/www/var/configuration/environment/shops/1/modules
    cp ./recipe/environment/1.yaml /var/www/var/configuration/environment/shops/1/modules/osc_paypal.yaml  
    vendor/bin/oe-console oe:module:install ./
    vendor/bin/oe-console oe:module:activate "{{ $ids }}"
    chmod +x .github/scripts/codestyle_check.sh


install_shop_with_modules:
  composer:
    root_url: ''


runscript: &runscript
  matrix:
    script: |
      [
        "osc_paypal:phpunit",
        "osc_paypal-node:test",
      ]
  osc_paypal:
    path: ''
  osc_paypal-node:
    path: 'tests/e2e'
    container_name: 'node'
    container_method: 'run'
    script_runner: 'npm run'
    custom_script: |
      docker compose run node npm install 

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "osc_paypal:phpmd",
        "osc_paypal:phpcs",
        "osc_paypal:phpstan"
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  project_key: 'OXID-eSales_{{ print $name }}'
  project_name: '{{ $org}}/{{ $name }}'
  parameters: |
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests
    -Donar.php.phpstan.reportPaths=coverage-reports/phpstan.report.json

finish:
  slack_title: '{{ print $name }} ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
