[{$smarty.block.parent}]
[{if $oViewConf->showPayPalCheckoutBannerOnProductDetailsPage()}]
    [{assign var="bannerAmount" value=$oxcmp_basket->getBruttoSum()}]
    [{if $oxcmp_basket->isPriceViewModeNetto()}]
        [{assign var="bannerAmount" value=$oxcmp_basket->getNettoSum()}]
    [{/if}]

    [{assign var="oPrice" value=$oDetailsProduct->getPrice()}]
    [{if $oDetailsProduct->isParentNotBuyable()}]
        [{assign var="oPrice" value=$oDetailsProduct->getVarMinPrice()}]
    [{/if}]
    [{assign var="productPrice" value=$oPrice->getPrice()}]
    [{assign var="bannerAmount" value=$bannerAmount+$productPrice}]
    [{include file="@osc_paypal/frontend/shared/installment_banners.tpl" amount=$bannerAmount selector=$oViewConf->getPayPalCheckoutBannerProductDetailsPageSelector()}]
[{/if}]
