[{$smarty.block.parent}]
[{if $oViewConf->showPayPalCheckoutBannerOnProductDetailsPage()}]
    [{assign var="bannerAmount" value=$oxcmp_basket->getBruttoSum()}]
    [{if $oxcmp_basket->isPriceViewModeNetto()}]
        [{assign var="bannerAmount" value=$oxcmp_basket->getNettoSum()}]
    [{/if}]

    [{if ($oxcmp_basket->getArtStockInBasket($oDetailsProduct->getId()) === 0) && !$oxcmp_basket->hasProductVariantInBasket($oDetailsProduct)}]
        [{assign var="oPrice" value=$oDetailsProduct->getPrice()}]
        [{if $oDetailsProduct->isParentNotBuyable()}]
            [{assign var="oPrice" value=$oDetailsProduct->getVarMinPrice()}]
        [{/if}]
        [{assign var="productPrice" value=$oPrice->getPrice()}]
        [{assign var="bannerAmount" value=$bannerAmount+$productPrice}]
    [{/if}]
    [{include file="@osc_paypal/frontend/shared/installment_banners.tpl" amount=$bannerAmount selector=$oViewConf->getPayPalCheckoutBannerProductDetailsPageSelector()}]
[{/if}]
