[{ assign var="shop"      value=$oEmailView->getShop() }]
[{ assign var="oViewConf" value=$oEmailView->getViewConfig() }]

[{block name="email_plain_pui_paymentinfo_billingheader"}]
    [{ oxmultilang ident="ORDER_SHIPPED_TO" suffix="COLON" }]
[{/block}]

[{block name="email_plain_pui_paymentinfo_billingaddress"}]
    [{ $order->oxorder__oxbillcompany->getRawValue() }]
    [{ $order->oxorder__oxbillfname->getRawValue() }] [{ $order->oxorder__oxbilllname->getRawValue() }]
    [{ $order->oxorder__oxbillstreet->getRawValue() }] [{ $order->oxorder__oxbillstreetnr->value }]
    [{ $order->oxorder__oxbillstateid->value }]
    [{ $order->oxorder__oxbillzip->value }] [{ $order->oxorder__oxbillcity->getRawValue() }]
[{/block}]

[{block name="email_plain_pui_paymentinfo_shippingheader"}]
    [{oxmultilang ident="SHIPPING_ADDRESS"}]
[{/block}]

[{block name="email_plain_pui_paymentinfo_shippingaddress"}]
    [{if $order->oxorder__oxdellname->value }]
    [{ $order->oxorder__oxdelcompany->getRawValue() }]
    [{ $order->oxorder__oxdelfname->getRawValue() }] [{ $order->oxorder__oxdellname->getRawValue() }]
    [{ $order->oxorder__oxdelstreet->getRawValue() }] [{ $order->oxorder__oxdelstreetnr->value }]
    [{ $order->oxorder__oxdelstateid->value }]
    [{ $order->oxorder__oxdelzip->value }] [{ $order->oxorder__oxdelcity->getRawValue() }]
    [{else}]
    [{ $order->oxorder__oxbillcompany->getRawValue() }]
    [{ $order->oxorder__oxbillfname->getRawValue() }] [{ $order->oxorder__oxbilllname->getRawValue() }]
    [{ $order->oxorder__oxbillstreet->getRawValue() }] [{ $order->oxorder__oxbillstreetnr->value }]
    [{ $order->oxorder__oxbillstateid->value }]
    [{ $order->oxorder__oxbillzip->value }] [{ $order->oxorder__oxbillcity->getRawValue() }]
    [{/if}]
[{/block}]

[{block name="email_plain_pui_paymentinfo_paymentheader"}]
    [{oxmultilang ident="PAYMENT_INFORMATION"}]
[{/block}]

[{block name="email_plain_pui_paymentinfo_paymentbody"}]
    [{oxmultilang ident="OSC_PAYPAL_PAYMENT_PUI_NOTE" suffix="COLON"}]
    [{oxmultilang ident="OSC_PAYPAL_PAYMENT_PUI_IBAN" suffix="COLON"}] [{ $puiPaymentDetails->iban }]
    [{oxmultilang ident="OSC_PAYPAL_PAYMENT_PUI_BIC" suffix="COLON"}] [{ $puiPaymentDetails->bic }]
    [{oxmultilang ident="OSC_PAYPAL_PAYMENT_PUI_BANKNAME" suffix="COLON"}] [{ $puiPaymentDetails->bank_name }]
    [{oxmultilang ident="OSC_PAYPAL_PAYMENT_PUI_ACCOUNTHOLDER" suffix="COLON"}] [{ $puiPaymentDetails->account_holder_name }]
    [{oxmultilang ident="OSC_PAYPAL_PAYMENT_PUI_REFERENCE" suffix="COLON"}] [{ $puiPaymentDetails->payment_reference }]
    [{oxmultilang ident="GRAND_TOTAL" suffix="COLON"}] [{oxprice price=$order->oxorder__oxtotalbrutsum->value currency=$currency}]
[{/block}]

[{block name="email_plain_pui_paymentinfo_oxordernr"}]
    [{ oxmultilang ident="ORDER_NUMBER" suffix="COLON" }] [{ $order->oxorder__oxordernr->value }]
[{/block}]

[{block name="email_plain_pui_paymentinfo_orderarticles"}]
    [{foreach from=$order->getOrderArticles(true) item=oOrderArticle}]
    [{ $oOrderArticle->oxorderarticles__oxamount->value }] [{ $oOrderArticle->oxorderarticles__oxtitle->getRawValue() }] [{ $oOrderArticle->oxorderarticles__oxselvariant->getRawValue() }]
    [{/foreach}]
[{/block}]

[{block name="email_plain_pui_paymentinfo_infofooter"}]
    [{ oxmultilang ident="YOUR_TEAM" args=$shop->oxshops__oxname->getRawValue()}]
[{/block}]

[{ oxcontent ident="oxemailfooterplain" }]