<?php

/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

$sLangName = 'English';

$aLang = [
    'charset'                                      => 'UTF-8',
    'paypal'                                       => 'PayPal',
    'OSC_PAYPAL_EDIT'                             => 'Edit',
    'OSC_PAYPAL_ACTIONS'                          => 'Actions',
    'OSC_PAYPAL_CAPTURE_PAYMENT'                  => 'Capture payment',
    'OSC_PAYPAL_ISSUE_REFUND'                     => 'Issue refund',
    'OSC_PAYPAL_SHOW_BALANCE_AFFECTING_RECORDS'   => 'Only balance affecting',
    'OSC_PAYPAL_REPORT_REFERENCE'                 => 'Report reference',
    'OSC_PAYPAL_TRANSACTION_TO_PRICE'             => 'Price to',
    'OSC_PAYPAL_TRANSACTION_FROM_PRICE'           => 'Price from',
    'OSC_PAYPAL_AVAILABLE_BALANCE'                => 'Available',
    'OSC_PAYPAL_PRODUCTS'                         => 'Product',
    'OSC_PAYPAL_WITHHELD_BALANCE'                 => 'Withheld',
    'OSC_PAYPAL_TOTAL_BALANCE'                    => 'Total',
    'OSC_PAYPAL_PRIMARY'                          => 'Primary',
    'OSC_PAYPAL_MORE'                             => 'More',
    'OSC_PAYPAL_LAST_REFRESH_TIME'                => 'Last refresh',
    'OSC_PAYPAL_CURRENCY_CODE'                    => 'Currency code',
    'OSC_PAYPAL_AS_OF_TIME'                       => 'As of time',
    'OSC_PAYPAL_PAYMENT_INSTRUMENT_CREDIT_CARD'   => 'Credit card',
    'OSC_PAYPAL_PAYMENT_INSTRUMENT_DEBIT_CARD'    => 'Debit card',
    'OSC_PAYPAL_TRANSACTION_STATUS_P'             => 'Pending',
    'OSC_PAYPAL_TRANSACTION_STATUS_F'             => 'Partially refunded',
    'OSC_PAYPAL_TRANSACTION_STATUS_D'             => 'Denied',
    'OSC_PAYPAL_TRANSACTION_STATUS_S'             => 'Completed',
    'OSC_PAYPAL_TRANSACTION_STATUS_V'             => 'Refunded',
    'OSC_PAYPAL_DISPUTE_STATUS_UNDER_REVIEW'      => 'Under Review',
    'OSC_PAYPAL_DATE_SELECT_HELP'                 => 'Maximum period of 31 days is allowed!',
    'OSC_PAYPAL_APPLY'                            => 'Apply',
    'OSC_PAYPAL_TRANSACTION_DATE_FROM'            => 'Date from',
    'OSC_PAYPAL_TRANSACTION_DATE_TO'              => 'Date to',
    'OSC_PAYPAL_TRANSACTION_TYPE'                 => 'Transaction type',
    'OSC_PAYPAL_TERMINAL_ID'                      => 'Terminal ID',
    'OSC_PAYPAL_PAYMENT_INSTRUMENT_TYPE'          => 'Instrument type',
    'OSC_PAYPAL_TRANSACTION_CURRENCY'             => 'Transaction currency',
    'OSC_PAYPAL_TRANSACTION_AMOUNT'               => 'Transaction amount',
    'OSC_PAYPAL_TRANSACTION_DATE'                 => 'Transaction date',
    'OSC_PAYPAL_STORE_ID'                         => 'Store ID',
    'OSC_PAYPAL_ACCOUNT_ID'                       => 'Account ID',
    'OSC_PAYPAL_TRANSACTION_ID'                   => 'Transaction ID',
    'OSC_PAYPAL_REFERENCE_ID'                     => 'Reference ID',
    'OSC_PAYPAL_REFERENCE_ID_TYPE'                => 'Reference ID type',
    'OSC_PAYPAL_EVENT_CODE'                       => 'Event code',
    'OSC_PAYPAL_INITIATION_DATE'                  => 'Initiated',
    'OSC_PAYPAL_UPDATED_DATE'                     => 'Updated',
    'OSC_PAYPAL_TRANSACTION_NOTE'                 => 'Note',
    'OSC_PAYPAL_BANK_REFERENCE_ID'                => 'Bank reference ID',
    'OSC_PAYPAL_CUSTOM_FIELD'                     => 'Custom field',
    'OSC_PAYPAL_CREDIT_TERM'                      => 'Credit term',
    'OSC_PAYPAL_INSTRUMENT_TYPE'                  => 'Instrument type',
    'OSC_PAYPAL_TRANSACTION_STATUS'               => 'Status',
    'OSC_PAYPAL_PAYMENT_TRACKING_ID'              => 'Payment tracking ID',
    'OSC_PAYPAL_PAYMENT_METHOD_TYPE'              => 'Payment method type',
    'OSC_PAYPAL_INSTRUMENT_SUB_TYPE'              => 'Instrument sub type',
    'OSC_PAYPAL_TRANSACTION_SUBJECT'              => 'Subject',
    'OSC_PAYPAL_PROTECTION_ELIGIBILITY'           => 'Protection eligibility',
    'tbclorder_paypal'                             => 'PayPal',
    // PayPal Config
    'OSC_PAYPAL_CONFIG'                           => 'Configuration',
    'OSC_PAYPAL_SUBSCRIBE'                        => 'PayPal Subscriptions',
    'OSC_PAYPAL_SUBSCRIBE_OPTIONS'                => 'PayPal Subscription Options',
    'PAYPAL_SUBSCRIBE_MAIN'                        => 'PayPal Subscriptions',
    'OSC_PAYPAL_BILLING_PLAN'                     => 'Billing Plans',
    'OSC_PAYPAL_BILLING_PLAN_MAIN'                => 'Billing Cycle',
    'OSC_PAYPAL_BILLING_PLAN_NAME'                => 'Billing Cycle Name',
    'OSC_PAYPAL_BILLING_PLAN_TYPE'                => 'Type',
    'OSC_PAYPAL_BILLING_PLAN_FIXED'               => 'Fixed',
    'OSC_PAYPAL_BILLING_PLAN_INFINITE'            => 'Infinite',
    'OSC_PAYPAL_BILLING_PLAN_DESCRIPTION'         => 'Description',
    'OSC_PAYPAL_BILLING_PLAN_DEFINITIONS'         => 'Definitions',
    'OSC_PAYPAL_BILLING_PLAN_AUTOMATICALLY_BILL'  => 'Automatically Bill Outstanding',
    'HELP_OSC_PAYPAL_BILLING_PLAN_AUTOMATICALLY_BILL'                              =>
        'Should PayPal automatically settle automatic invoices?',
    'OSC_PAYPAL_BILLING_PLAN_SETUP_FEE'           => 'Setup Fee',
    'OSC_PAYPAL_BILLING_PLAN_FAILURE_ACTION'      => 'Setup Failure Action',
    'HELP_OSC_PAYPAL_BILLING_PLAN_FAILURE_ACTION' =>
        'Should an error occur when setting up the subscription. Should the subscription be created anyway
        (<b>Continue</b>), or the process canceled (<b>Cancel</b>)?',
    'OSC_PAYPAL_BILLING_PLAN_ACTION_CONTINUE'     => 'Continue',
    'OSC_PAYPAL_BILLING_PLAN_ACTION_CANCEL'       => 'Cancel',
    'OSC_PAYPAL_BILLING_PLAN_FAILURE_THRESHOLD'   => 'Payment Failure Threshold',
    'HELP_OSC_PAYPAL_BILLING_PLAN_FAILURE_THRESHOLD'                                =>
        'How often should a payment be tried before it is canceled?',
    'OSC_PAYPAL_BILLING_PLAN_TAX'                 => 'Tax',
    'OSC_PAYPAL_BILLING_PLAN_TAX_PERCENTAGE'      => 'Tax Percentage',
    'OSC_PAYPAL_BILLING_PLAN_TAX_INCLUSIVE'       => 'Tax Inclusive',
    'OSC_PAYPAL_BILLING_PLAN_PAYPAL_ID'           => 'PayPal ID',
    'OSC_PAYPAL_BILLING_PLAN_BILLING_CYCLES'      => 'Assigned Billing Cycles',
    'OSC_PAYPAL_BILLING_PLAN_PRICE'               => 'Price',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY'           => 'Frequency',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_DAY'       => 'daily',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_WEEK'      => 'weekly',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_SEMI_MONTH' => 'semi weekly',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_MONTH'     => 'monthly',
    'OSC_PAYPAL_BILLING_PLAN_FREQUENCY_YEAR'      => 'yearly',
    'OSC_PAYPAL_BILLING_PLAN_TENURE'              => 'Tenure',
    'OSC_PAYPAL_BILLING_PLAN_SEQUENCE'            => 'Sequence',
    'OSC_PAYPAL_BILLING_PLAN_CYCLES'              => 'Cycles',
    'OSC_PAYPAL_BILLING_PLAN_TOTAL_CYCLES'        => 'Total Cycles',
    'OSC_PAYPAL_BILLING_PLAN_ACTIONS'             => 'Actions',
    'OSC_PAYPAL_BILLING_PLAN_NO_PLANS'            => 'No Billing Plans',
    'OSC_PAYPAL_BILLING_PLAN_ADD'                 => 'Add Billing Plan',
    'OSC_PAYPAL_BILLING_PLAN_ADD_CYCLES'          => 'Add Billing Cycles',
    'OSC_PAYPAL_BILLING_PLAN_YES'                 => 'Yes',
    'OSC_PAYPAL_BILLING_PLAN_NO'                  => 'No',
    'OSC_PAYPAL_BILLING_PLAN_SUBSCRIPTION_PROD'   => 'Subscription Product',
    'OSC_PAYPAL_TRANSACTIONS'                     => 'Transactions',
    'OSC_PAYPAL_BALANCES'                         => 'Balances',
    'OSC_PAYPAL_GENERAL'                          => 'General',
    'OSC_PAYPAL_WEBHOOK_ID'                       => 'Webhook ID',
    'OSC_PAYPAL_OPMODE'                           => 'Operation mode',
    'OSC_PAYPAL_OPMODE_LIVE'                      => 'Live',
    'OSC_PAYPAL_OPMODE_SANDBOX'                   => 'Sandbox',
    'OSC_PAYPAL_CLIENT_ID'                        => 'Client ID',
    'OSC_PAYPAL_CLIENT_SECRET'                    => 'Secret',
    'OSC_PAYPAL_CREDENTIALS'                      => 'API credentials',
    'OSC_PAYPAL_LIVE_CREDENTIALS'                 => 'Live API credentials',
    'OSC_PAYPAL_SANDBOX_CREDENTIALS'              => 'Sandbox API credentials',
    'OSC_PAYPAL_LIVE_BUTTON_CREDENTIALS'          => 'SignUp Merchant Integration (Live)',
    'OSC_PAYPAL_SANDBOX_BUTTON_CREDENTIALS'       => 'SignUp Merchant Integration (Sandbox)',
    'OSC_PAYPAL_ERR_CONF_INVALID'                 =>
        'One or more configuration values are either not set or incorrect. Please double check them.<br>
        <b>Module inactive.</b>',
    'OSC_PAYPAL_CONF_VALID'                       => 'Configuration values OK.<br><b>Module is active</b>',
    'OSC_PAYPAL_BUTTON_PLACEMEMT_TITLE'           => 'Button placement settings',
    'OSC_PAYPAL_PRODUCT_DETAILS_BUTTON_PLACEMENT' => 'Product details page',
    'OSC_PAYPAL_BASKET_BUTTON_PLACEMENT'          => 'Basket',
    'OSC_PAYPAL_CHECKOUT_PLACEMENT'               => 'Payment Page (Checkout)',
    'OSC_PAYPAL_EXPRESS_LOGIN_TITLE'              => 'Login with PayPal',
    'OSC_PAYPAL_LOGIN_WITH_PAYPAL_EMAIL'          => 'Automatically log in to shop during checkout',
    'HELP_OSC_PAYPAL_EXPRESS_LOGIN'               => 'In case there is already a shop user registered with password to the same mail address as the the PayPal mail,
        it is possible to be autonmatically be logged in to shop when logging in to PayPal. This behavior may not be in the 
        security interests of your customers',

    'HELP_OSC_PAYPAL_BUTTON_PLACEMEMT'            => 'Toggle the display of PayPal buttons',
    'HELP_OSC_PAYPAL_CREDENTIALS'                 =>
        'If you already have the API credentials, you can enter them directly.<br>
        If you do not yet have any API data and the input fields are still empty, you can also use the
        displayed button for a convenient link.',
    'HELP_OSC_PAYPAL_CLIENT_ID'                   => 'Client ID for live mode.',
    'HELP_OSC_PAYPAL_CLIENT_SECRET'               => 'Secret for live mode.',
    'HELP_OSC_PAYPAL_SANDBOX_CLIENT_ID'           => 'Client ID for sandbox mode.',
    'HELP_OSC_PAYPAL_SANDBOX_CLIENT_SECRET'       => 'Secret for sandbox mode. Please enter the password twice.',
    'HELP_OSC_PAYPAL_SANDBOX_WEBHOOK_ID'          =>
        'The ID of the sandbox-webhook as configured in your Developer Portal account',
    'HELP_OSC_PAYPAL_OPMODE'                      =>
        'To configure and test PayPal, use Sandbox (test). When you\'re ready
        to receive real transactions, switch to Production (live).',
    'HELP_OSC_PAYPAL_WEBHOOK_ID'                  =>
        'The ID of the webhook as configured in your Developer Portal account',

    // PayPal ORDER
    'OSC_PAYPAL_AMOUNT'                           => 'Amount',
    'OSC_PAYPAL_SHOP_PAYMENT_STATUS'              => 'Shop payment status',
    'OSC_PAYPAL_ORDER_PRICE'                      => 'Full order price',
    'OSC_PAYPAL_ORDER_PRODUCTS'                   => 'Ordered products',
    'OSC_PAYPAL_CAPTURED'                         => 'Captured',
    'OSC_PAYPAL_REFUNDED'                         => 'Refunded',
    'OSC_PAYPAL_CAPTURED_NET'                     => 'Resulting payment amount',
    'OSC_PAYPAL_CAPTURED_AMOUNT'                  => 'Captured amount',
    'OSC_PAYPAL_REFUNDED_AMOUNT'                  => 'Refunded amount',
    'OSC_PAYPAL_VOIDED_AMOUNT'                    => 'Voided amount',
    'OSC_PAYPAL_MONEY_CAPTURE'                    => 'Money capture',
    'OSC_PAYPAL_MONEY_REFUND'                     => 'Money refund',
    'OSC_PAYPAL_CAPTURE'                          => 'Capture',
    'OSC_PAYPAL_REFUND'                           => 'Refund',
    'OSC_PAYPAL_DETAILS'                          => 'Details',
    'OSC_PAYPAL_AUTHORIZATION'                    => 'Authorization',
    'OSC_PAYPAL_CANCEL_AUTHORIZATION'             => 'Void',
    'OSC_PAYPAL_PAYMENT_HISTORY'                  => 'PayPal history',
    'OSC_PAYPAL_HISTORY_DATE'                     => 'Date',
    'OSC_PAYPAL_HISTORY_ACTION'                   => 'Action',
    'OSC_PAYPAL_HISTORY_PAYPAL_STATUS'            => 'PayPal status',
    'OSC_PAYPAL_HISTORY_PAYPAL_STATUS_HELP'       =>
        'Payment status returned from PayPal. For more details see:
        <a href="https://www.paypal.com/webapps/helpcenter/article/?articleID=94021&m=SRE" target="_blank">
            PayPal status
        </a>',
    'OSC_PAYPAL_HISTORY_COMMENT'                  => 'Comment',
    'OSC_PAYPAL_HISTORY_NOTICE'                   => 'Note',
    'OSC_PAYPAL_HISTORY_NOTICE_TEXT'              => 'In case of error, please see "Details" for more information',
    'OSC_PAYPAL_MONEY_ACTION_FULL'                => 'full',
    'OSC_PAYPAL_MONEY_ACTION_PARTIAL'             => 'partial',
    'OSC_PAYPAL_LIST_STATUS_ALL'                  => 'All',
    'OSC_PAYPAL_STATUS_COMPLETED'                 => 'Completed',
    'OSC_PAYPAL_STATUS_DECLINED'                  => 'Declined',
    'OSC_PAYPAL_STATUS_PARTIALLY_REFUNDED'        => 'Partially refunded',
    'OSC_PAYPAL_STATUS_PENDING'                   => 'Pending',
    'OSC_PAYPAL_STATUS_REFUNDED'                  => 'Refunded',
    'OSC_PAYPAL_PAYMENT_METHOD'                   => 'Payment method',
    'OSC_PAYPAL_CLOSE'                            => 'Close',
    'OSC_PAYPAL_COMMENT'                          => 'Comment',
    'OSC_PAYPAL_RESPONSE_FROM_PAYPAL'             => 'Error message from PayPal: ',
    'OSC_PAYPAL_AUTHORIZATIONID'                  => 'Authorization ID',
    'OSC_PAYPAL_TRANSACTIONID'                    => 'Transaction ID',
    'OSC_PAYPAL_REFUND_AMOUNT'                    => 'Refund amount',
    'OSC_PAYPAL_INVOICE_ID'                       => 'Invoice No',
    'OSC_PAYPAL_NOTE_TO_BUYER'                    => 'Note to buyer',
    'OSC_PAYPAL_REFUND_ALL'                       => 'Refund all',
    'OSC_PAYPAL_SUBSCRIPTION'                     => 'Subscription',
    'OSC_PAYPAL_SUBSCRIPTION_ID'                  => 'Subscription ID',
    'OSC_PAYPAL_SUBSCRIPTION_PLAN_ID'             => 'Plan ID',
    'OSC_PAYPAL_SUBSCRIPTION_START_TIME'          => 'Start time',
    'OSC_PAYPAL_SUBSCRIPTION_QUANTITY'            => 'Quantity',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS'              => 'Status',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_CHANGE_NOTE'  => 'Status change note',
    'OSC_PAYPAL_SUBSCRIPTION_CREATE_TIME'         => 'Created',
    'OSC_PAYPAL_SUBSCRIPTION_UPDATE_TIME'         => 'Updated',
    'OSC_PAYPAL_SUBSCRIBER_PAYER_ID'              => 'Payer ID',
    'OSC_PAYPAL_FIRST_NAME'                       => 'First name',
    'OSC_PAYPAL_LAST_NAME'                        => 'Last name',
    'OSC_PAYPAL_FULL_NAME'                        => 'Full name',
    'OSC_PAYPAL_EMAIL'                            => 'Email',
    'OSC_PAYPAL_ADDRESS_LINE_1'                   => 'Address line 1',
    'OSC_PAYPAL_ADDRESS_LINE_2'                   => 'Address line 2',
    'OSC_PAYPAL_ADDRESS_LINE_3'                   => 'Address line 3',
    'OSC_PAYPAL_ADMIN_AREA_1'                     => 'Province, State, or ISO-subdivision',
    'OSC_PAYPAL_ADMIN_AREA_2'                     => 'City',
    'OSC_PAYPAL_ADMIN_AREA_3'                     => 'Sub-locality, Suburb, Neighborhood or District',
    'OSC_PAYPAL_ADMIN_AREA_4'                     => 'The neighborhood, ward, or district',
    'OSC_PAYPAL_POSTAL_CODE'                      => 'Postal code',
    'OSC_PAYPAL_COUNTRY_CODE'                     => 'Country code',
    'OSC_PAYPAL_SUBSCRIPTION_NEXT_BILLING_TIME'   => 'Next billing',
    'OSC_PAYPAL_SUBSCRIPTION_NEXT_PAYMENT_TIME'   => 'Next payment',
    'OSC_PAYPAL_SUBSCRIPTION_FINAL_PAYMENT'       => 'Final payment',
    'OSC_PAYPAL_SUBSCRIPTION_FAILED_PAYMENT_COUNT'                                  => 'Failed payments',
    'OSC_PAYPAL_SUBSCRIPTION_LAST_FAILED_PAYMENT' => 'Last failed payment',
    'OSC_PAYPAL_SUBSCRIPTION_TOTAL_PAID_AMOUNT'   => 'Total paid',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_UPDATE_TIME'  => 'Status updated',
    'OSC_PAYPAL_SUBSCRIBER'                       => 'Subscriber',
    'OSC_PAYPAL_SHIPPING'                         => 'Shipping',
    'OSC_PAYPAL_BILLING'                          => 'Billing',
    'OSC_PAYPAL_SUBSCRIPTIONS'                    => 'Subscriptions',
    'OSC_PAYPAL_SUBSCRIPTIONS_SHORT'              => 'PP Subscr.',
    'OSC_PAYPAL_SUBSCRIPTION_OUTSTANDING_BALANCE' => 'Outstanding balance',
    'OSC_PAYPAL_SUBSCRIPTION_LAST_PAYMENT'        => 'Last payment amount',
    'OSC_PAYPAL_SUBSCRIPTION_LAST_PAYMENT_TIME'   => 'Last payment',
    'OSC_PAYPAL_SUBSCRIPTION_FAILED_PAYMENT_REASON'                                 => 'Reason',
    'OSC_PAYPAL_SUBSCRIPTION_FAILED_PAYMENT_RETRY_TIME'                             => 'Retry',
    'OSC_PAYPAL_TIME'                             => 'Time',
    'OSC_PAYPAL_TENURE_TYPE'                      => 'Tenure type',
    'OSC_PAYPAL_TENURE_TYPE_TRIAL'                => 'Trial',
    'OSC_PAYPAL_TENURE_TYPE_REGULAR'              => 'Regular',
    'OSC_PAYPAL_SEQUENCE'                         => 'Sequence',
    'OSC_PAYPAL_CYCLES_COMPLETED'                 => 'Cycles completed',
    'OSC_PAYPAL_CURRENT_PRICING_SCHEME_VERSION'                                     => 'Pricing scheme version',
    'OSC_PAYPAL_TOTAL_CYCLES'                     => 'Total cycles',
    'OSC_PAYPAL_CYCLES_REMAINING'                 => 'Cycles remaining',
    'OSC_PAYPAL_SUBSCRIPTION_STARTS'              => 'Starts',
    'OSC_PAYPAL_SUBSCRIPTION_EMAIL'               => 'Email',
    'OSC_PAYPAL_SUBSCRIPTION_UPDATED'             => 'Updated',
    'OSC_PAYPAL_SUBSCRIPTION_CREATED'             => 'Created',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_UPDATED'      => 'Status updated',
    'OSC_PAYPAL_STATUS_CREATED'                   => 'Created',
    'OSC_PAYPAL_STATUS_INACTIVE'                  => 'Inactive',
    'OSC_PAYPAL_STATUS_ACTIVE'                    => 'Active',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_APPROVAL_PENDING'                               => 'Approval pending',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_APPROVED'     => 'Approved',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_ACTIVE'       => 'Active',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_SUSPENDED'    => 'Suspended',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_CANCELLED'    => 'Cancelled',
    'OSC_PAYPAL_SUBSCRIPTION_STATUS_EXPIRED'      => 'Expired',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_ID'      => 'Transaction ID',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_STATUS'  => 'Transaction status',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_GROSS_AMOUNT'                              => 'Gross amount',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_NET_AMOUNT'                                => 'Net amount',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_FEE_AMOUNT'                                => 'Fee amount',
    'OSC_PAYPAL_SUBSCRIPTION_TRANSACTION_DATE'    => 'Date',
    'OSC_PAYPAL_FROM'                             => 'From',
    'OSC_PAYPAL_TO'                               => 'To',
    'OSC_PAYPAL_BACK'                             => 'Back',
    'OSC_PAYPAL_NOTE'                             => 'Note',
    'OSC_PAYPAL_CAPTURE_OUTSTANDING_FEES'         => 'Capture outstanding fees',
    'OSC_PAYPAL_DISPUTES'                         => 'Disputes',
    'OSC_PAYPAL_DISPUTE_START_TIME'               => 'Start time',
    'OSC_PAYPAL_DISPUTE_TRANSACTION_ID'           => 'Transaction ID',
    'OSC_PAYPAL_DISPUTE_STATE'                    => 'State',
    'OSC_PAYPAL_DISPUTE_STATUS_REQUIRED_ACTION'   => 'Requires action',
    'OSC_PAYPAL_DISPUTE_STATUS_REQUIRED_OTHER_PARTY_ACTION'                         => 'Requires other party action',
    'OSC_PAYPAL_DISPUTE_STATUS_UNDER_PAYPAL_REVIEW'                                 => 'Under PayPal review',
    'OSC_PAYPAL_DISPUTE_STATUS_RESOLVED'          => 'Resolved',
    'OSC_PAYPAL_DISPUTE_STATUS_OPEN_INQUIRIES'    => 'Open',
    'OSC_PAYPAL_DISPUTE_STATUS_APPEALABLE'        => 'Appealable',
    'OSC_PAYPAL_DISPUTE_STATUS_WAITING_FOR_BUYER_RESPONSE'                          => 'Waiting for buyer response',
    'OSC_PAYPAL_DISPUTE_STATUS_WAITING_FOR_SELLER_RESPONSE'                         => 'Waiting for seller response',
    'OSC_PAYPAL_DISPUTE_ID'                       => 'Dispute ID',
    'OSC_PAYPAL_DISPUTE_STATUS'                   => 'Status',
    'OSC_PAYPAL_DISPUTE_AMOUNT'                   => 'Amount',
    'OSC_PAYPAL_DISPUTE_CREATE_TIME'              => 'Create time',
    'OSC_PAYPAL_DISPUTE_UPDATE_TIME'              => 'Update time',
    'OSC_PAYPAL_DISPUTE_REASON'                   => 'Reason',
    'OSC_PAYPAL_DISPUTE_REASON_MERCHANDISE_OR_SERVICE_NOT_RECEIVED'                 =>
        'Merchandise or service not received',
    'OSC_PAYPAL_DISPUTE_REASON_MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED'             =>
        'Merchandise or service not as described',
    'OSC_PAYPAL_DISPUTE_REASON_UNAUTHORISED'      => 'Unauthorised',
    'OSC_PAYPAL_DISPUTE_REASON_CREDIT_NOT_PROCESSED'                                => 'Credit not processed',
    'OSC_PAYPAL_DISPUTE_REASON_CREDIT_DUPLICATE_TRANSACTION'                        => 'Credit duplicate transaction',
    'OSC_PAYPAL_DISPUTE_REASON_INCORRECT_AMOUNT'  => 'Incorrect amount',
    'OSC_PAYPAL_DISPUTE_REASON_PAYMENT_BY_OTHER_MEANS'                              => 'Payment by other means',
    'OSC_PAYPAL_DISPUTE_REASON_CANCELED_RECURRING_BILLING'                          => 'Canceled recurring billing',
    'OSC_PAYPAL_DISPUTE_REASON_PROBLEM_WITH_REMITTANCE'                             => 'Problem with remittance',
    'OSC_PAYPAL_DISPUTE_REASON_OTHER'             => 'Other',
    'OSC_PAYPAL_REASON'                           => 'Reason',
    'OSC_PAYPAL_STATUS'                           => 'Status',
    'OSC_PAYPAL_DISPUTE_INVOICE_ID'               => 'Invoice ID',
    'OSC_PAYPAL_DISPUTE_OFFER_TYPE'               => 'Offer type',
    'OSC_PAYPAL_DISPUTE_NOTE'                     => 'Note',
    'OSC_PAYPAL_DISPUTE_OFFER_AMOUNT'             => 'Offer amount',
    'OSC_PAYPAL_SUBSCRIPTION_BILLING'             => 'Billing',
    'OSC_PAYPAL_SEND'                             => 'Send',
    'OSC_PAYPAL_DISPUTE_REFUND'                   => 'Refund',
    'OSC_PAYPAL_DISPUTE_REFUND_WITH_RETURN'       => 'Refund with return',
    'OSC_PAYPAL_DISPUTE_REFUND_WITH_REPLACEMENT'  => 'Refund with replacement',
    'OSC_PAYPAL_DISPUTE_REPLACEMENT_WITHOUT_REFUND'                                 => 'Replacement without refund',
    'OSC_PAYPAL_SUBSCRITION_PART_NOTE'            =>
        'This is a partial delivery of a subscription. The information about this subscription can be found in the main order no.',
    // Errors
    'OSC_PAYPAL_ERROR_NOT_PAID_WITH_PAYPAL'       => 'Order not paid using PayPal',
    'OSC_PAYPAL_ERROR_INVALID_RESOURCE_ID'        => 'Specified resource ID does not exist.',
    'OSC_PAYPAL_ERROR_DUPLICATE_INVOICE_ID'       => 'Duplicate Invoice ID detected.',
    'OSC_PAYPAL_MESSAGES'                         => 'Messages',
    'OSC_PAYPAL_SEND_MESSAGES'                    => 'Send Messages',
    'OSC_PAYPAL_MAKE_OFFER'                       => 'Make Offer',
    'OSC_PAYPAL_ESCALATE'                         => 'Escalate',
    'OSC_PAYPAL_HISTORY'                          => 'History',
    'OSC_PAYPAL_RESOLVED_BUYER_FAVOUR'            => 'Resolved in favour of Buyer',
    'OSC_PAYPAL_RESOLVED_SELLER_FAVOUR'           => 'Resolved in favour of Seller',
    'OSC_PAYPAL_PRODUCT_ID'                       => 'Product-ID',
    'OSC_PAYPAL_PRODUCT_NAME'                     => 'Product Name',
    'HELP_OSC_PAYPAL_PRODUCT_NAME'                =>
        'The product name is also transferred to PayPal for better identification in the PayPal account.',
    'OSC_PAYPAL_PRODUCT_DESCRIPTION'              => 'Description',
    'HELP_OSC_PAYPAL_PRODUCT_DESCRIPTION'         =>
        'The Description is also transferred to PayPal for better identification in the PayPal account.',
    'OSC_PAYPAL_PRODUCT_TYPE'                     => 'Product-Type',
    'OSC_PAYPAL_PRODUCT_TYPE_CATEGORY'            => 'Type-Category',
    'OSC_PAYPAL_PRODUCT_URL'                      => 'URL',
    'OSC_PAYPAL_PRODUCT_IMAGE'                    => 'Image',
    'HELP_OSC_PAYPAL_PRODUCT_IMAGE'               =>
        'The Image is also transferred to PayPal for better identification in the PayPal account.',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_SHIPMENT_NOT_ARRIVED'                        => 'Shipment has not arrived',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_FRAUDULENT_SELLER'                           => 'Fraudulent Seller',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_FAILED_NEGOTIATION'                          => 'Failed Negotiation',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_INCONCLUSIVE_NEGOTIATION'                    => 'Inconclusive negotiation',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_REFUND_NOT_RECEIVED'                         => 'Refund not received',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_REFUND_AMOUNT_IS_DIFFERENT'                  => 'Refund Amount is different',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_TRACKING_ID_INVALID'                         => 'Tracking ID is invalid',
    'OSC_PAYPAL_BUYER_ESCALATION_REASON_OTHER'    => 'Other',
    'OSC_PAYPAL_EVIDENCE'                         => 'Evidence',
    'OSC_PAYPAL_PROVIDE_EVIDENCE'                 => 'Provide Evidence',
    'OSC_PAYPAL_UPLOAD_FILE'                      => 'Upload File',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_FULFILLMENT'                                  => 'Proof Of Fulfillment',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_REFUND'    => 'Proof Of Refund',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_DELIVERY_SIGNATURE'                           => 'Proof Of Delivery Signature',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_RECEIPT_COPY'                                 => 'Proof Of Receipt Copy',
    'OSC_PAYPAL_EVIDENCE_TYPE_RETURN_POLICY'      => 'Return Policy',
    'OSC_PAYPAL_EVIDENCE_TYPE_BILLING_AGREEMENT'  => 'Billing Agreement',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_RESHIPMENT'                                   => 'Proof Of Reshipment',
    'OSC_PAYPAL_EVIDENCE_TYPE_ITEM_DESCRIPTION'   => 'Item Description',
    'OSC_PAYPAL_EVIDENCE_TYPE_POLICE_REPORT'      => 'Police Report',
    'OSC_PAYPAL_EVIDENCE_TYPE_AFFIDAVIT'          => 'Affidavit',
    'OSC_PAYPAL_EVIDENCE_TYPE_PAID_WITH_OTHER_METHOD'                                => 'Paid With Other Method',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_CONTRACT'   => 'Copy Of Contract',
    'OSC_PAYPAL_EVIDENCE_TYPE_TERMINAL_ATM_RECEIPT'                                  => 'Terminal Atm Receipt',
    'OSC_PAYPAL_EVIDENCE_TYPE_PRICE_DIFFERENCE_REASON'                               => 'Price Difference Reason',
    'OSC_PAYPAL_EVIDENCE_TYPE_SOURCE_CONVERSION_RATE'                                => 'Source Conversion Rate',
    'OSC_PAYPAL_EVIDENCE_TYPE_BANK_STATEMENT'                                        => 'Bank Statement',
    'OSC_PAYPAL_EVIDENCE_TYPE_CREDIT_DUE_REASON'  => 'Credit Due Reason',
    'OSC_PAYPAL_EVIDENCE_TYPE_REQUEST_CREDIT_RECEIPT'                                => 'Request Credit Receipt',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_RETURN'                                       => 'Proof Of Return',
    'OSC_PAYPAL_EVIDENCE_TYPE_CREATE'             => 'Create',
    'OSC_PAYPAL_EVIDENCE_TYPE_CHANGE_REASON'      => 'Change Reason',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_REFUND_OUTSIDE_PAYPAL'                        =>
        'Proof Of Refund Outside PayPal',
    'OSC_PAYPAL_EVIDENCE_TYPE_RECEIPT_OF_MERCHANDISE'                                => 'Receipt Of Merchandise',
    'OSC_PAYPAL_EVIDENCE_TYPE_CUSTOMS_DOCUMENT'   => 'Customs Document',
    'OSC_PAYPAL_EVIDENCE_TYPE_CUSTOMS_FEE_RECEIPT'                                   => 'Customs Fee Receipt',
    'OSC_PAYPAL_EVIDENCE_TYPE_INFORMATION_ON_RESOLUTION'                             => 'Information On Resolution',
    'OSC_PAYPAL_EVIDENCE_TYPE_ADDITIONAL_INFORMATION_OF_ITEM'                        =>
        'Additional Information Of Item',
    'OSC_PAYPAL_EVIDENCE_TYPE_DETAILS_OF_PURCHASE'                                   => 'Details Of Purchase',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_SIGNIFICANT_DIFFERENCE'                       =>
        'Proof Of Significant Difference',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_SOFTWARE_OR_SERVICE_NOT_AS_DESCRIBED'         =>
        'Proof Of Software Or Service Not As Described',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_CONFISCATION'                                 => 'Proof Of Confiscation',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_DAMAGE'     => 'Proof Of Damage',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_LAW_ENFORCEMENT_AGENCY_REPORT'                 =>
        'Copy Of Law Enforcement Agency Report',
    'OSC_PAYPAL_EVIDENCE_TYPE_ADDITIONAL_PROOF_OF_SHIPMENT'                          => 'Additional Proof Of Shipment',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_DENIAL_BY_CARRIER'                            => 'Proof Of Denial By Carrier',
    'OSC_PAYPAL_EVIDENCE_TYPE_THIRDPARTY_PROOF_FOR_DAMAGE_OR_SIGNIFICANT_DIFFERENCE' =>
        'Thirdparty Proof For Damage Or Significant Difference',
    'OSC_PAYPAL_EVIDENCE_TYPE_VALID_SUPPORTING_DOCUMENT'                             => 'Valid Supporting Document',
    'OSC_PAYPAL_EVIDENCE_TYPE_LEGIBLE_SUPPORTING_DOCUMENT'                           => 'Legible Supporting Document',
    'OSC_PAYPAL_EVIDENCE_TYPE_RETURN_TRACKING_INFORMATION'                           => 'Return Tracking Information',
    'OSC_PAYPAL_EVIDENCE_TYPE_DELIVERY_RECEIPT'    => 'Delivery Receipt',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_INSTORE_RECEIPT'                              => 'Proof Of Instore Receipt',
    'OSC_PAYPAL_EVIDENCE_TYPE_ADDITIONAL_TRACKING_INFORMATION'                       =>
        'Additional Tracking Information',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_SHIPMENT_POSTAGE'                             => 'Proof Of Shipment Postage',
    'OSC_PAYPAL_EVIDENCE_TYPE_ONLINE_TRACKING_INFORMATION'                           => 'Online Tracking Information',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_OF_INSTORE_REFUND'                               => 'Proof Of Instore Refund',
    'OSC_PAYPAL_EVIDENCE_TYPE_PROOF_FOR_SOFTWARE_OR_SERVICE_DELIVERED'               =>
        'Proof For Software Or Service Delivered',
    'OSC_PAYPAL_EVIDENCE_TYPE_RETURN_ADDRESS_FOR_SHIPPING'                           => 'Return Address For Shipping',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_THE_EPARCEL_MANIFEST'                          => 'Copy Of The Eparcel Manifest',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_SHIPPING_MANIFEST'                             => 'Copy Of Shipping Manifest',
    'OSC_PAYPAL_EVIDENCE_TYPE_APPEAL_AFFIDAVIT'                                      => 'Appeal Affidavit',
    'OSC_PAYPAL_EVIDENCE_TYPE_RECEIPT_OF_REPLACEMENT'                                => 'Receipt Of Replacement',
    'OSC_PAYPAL_EVIDENCE_TYPE_COPY_OF_DRIVERS_LICENSE'                               => 'Copy Of Drivers License',
    'OSC_PAYPAL_EVIDENCE_TYPE_ACCOUNT_CHANGE_INFORMATION'                            => 'Account Change Information',
    'OSC_PAYPAL_EVIDENCE_TYPE_DELIVERY_ADDRESS'                                      => 'Delivery Address',
    'OSC_PAYPAL_EVIDENCE_TYPE_CONFIRMATION_OF_RESOLUTION'                            => 'Confirmation Of Resolution',
    'OSC_PAYPAL_EVIDENCE_TYPE_MERCHANT_RESPONSE'                                     => 'Merchant Response',
    'OSC_PAYPAL_EVIDENCE_TYPE_PERMISSION_DESCRIPTION'                                => 'Permission Description',
    'OSC_PAYPAL_EVIDENCE_TYPE_STATUS_OF_MERCHANDISE'                                 => 'Status Of Merchandise',
    'OSC_PAYPAL_EVIDENCE_TYPE_LOST_CARD_DETAILS'                                     => 'Lost Card Details',
    'OSC_PAYPAL_EVIDENCE_TYPE_LAST_VALID_TRANSACTION_DETAILS'                        =>
        'Last Valid Transaction Details',
    'OSC_PAYPAL_EVIDENCE_TYPE_OTHER'              => 'Other',
    'OSC_PAYPAL_EVIDENCE_TYPE'                    => 'Evidence Type',
    'OSC_PAYPAL_EVIDENCE_DOCUMENT'                => 'Document',
    'OSC_PAYPAL_FILTER'                           => 'Filter',
    'OSC_PAYPAL_CREATED'                          => 'created',
    'OSC_PAYPAL_ME'                               => 'Me',
    'OSC_PAYPAL_COPY'                             => 'Copy',

    'TOOLTIPS_OSC_PAYPAL_EDITSUBSCRIPTION'        => 'Edit Billing-Plan',
    'TOOLTIPS_OSC_PAYPAL_DEACTIVATESUBSCRIPTION'  => 'Deactivate Billing-Plan',

    // PSPAYPAL-491 -->
    'OSC_PAYPAL_BANNER_CREDENTIALS'                => 'Banner settings',
    'OSC_PAYPAL_BANNER_INFOTEXT'                   => 'Offer your customers PayPal installment payment with 0% effective annual interest. <a href="https://www.paypal.com/de/webapps/mpp/installments" target="_blank">Read more</a>.',
    'OSC_PAYPAL_BANNER_SHOW_ALL'                   => 'Enable installment banners',
    'HELP_OSC_PAYPAL_BANNER_SHOP_MODULE_SHOW_ALL'  => 'Check this option to enable the banner feature.',
    'OSC_PAYPAL_BANNER_STARTPAGE'                   => 'Show installment banner on start page',
    'OSC_PAYPAL_BANNER_STARTPAGESELECTOR'           => 'CSS selector of the start page after which the banner is displayed.',
    'HELP_OSC_PAYPAL_BANNER_STARTPAGESELECTOR'      => 'Default values for Flow and Wave themes are: \'#wrapper .row\' and \'#wrapper .container\' respectively. After these CSS selectors the banner is displayed.',
    'OSC_PAYPAL_BANNER_CATEGORYPAGE'                => 'Show installment banner on category pages',
    'OSC_PAYPAL_BANNER_CATEGORYPAGESELECTOR'        => 'CSS selector of the category pages after which the banner is displayed.',
    'HELP_OSC_PAYPAL_BANNER_CATEGORYPAGESELECTOR'   => 'Default values for Flow and Wave themes are: \'.page-header\' and \'.page-header\' respectively. After these CSS selectors the banner is displayed.',
    'OSC_PAYPAL_BANNER_SEARCHRESULTSPAGE'           => 'Show installment banner on search results pages',
    'OSC_PAYPAL_BANNER_SEARCHRESULTSPAGESELECTOR'   => 'CSS selector of the search results pages after which the banner is displayed.',
    'HELP_OSC_PAYPAL_BANNER_SEARCHRESULTSPAGESELECTOR' => 'Default values for Flow and Wave themes are: \'#content .page-header .clearfix\' and \'.page-header\' respectively. After these CSS selectors the banner is displayed.',
    'OSC_PAYPAL_BANNER_DETAILSPAGE'                 => 'CSS selector of the product detail pages after which the banner is displayed.',
    'OSC_PAYPAL_BANNER_DETAILSPAGESELECTOR'         => 'CSS-Selektor der Detailseiten hinter dem das Banner angezeigt wird.',
    'HELP_OSC_PAYPAL_BANNER_DETAILSPAGESELECTOR'    => 'Default values for Flow and Wave themes are: \'.detailsParams\' and \'#detailsItemsPager\' respectively. After these CSS selectors the banner is displayed.',
    'OSC_PAYPAL_BANNER_CHECKOUTPAGE'                => 'Show installment banner on checkout pages',
    'OSC_PAYPAL_BANNER_CARTPAGESELECTOR'            => 'CSS selector of the "Cart" page (checkout step 1) after which the banner is displayed.',
    'HELP_OSC_PAYPAL_BANNER_CARTPAGESELECTOR'       => 'Default values for Flow and Wave themes are: \'.cart-buttons\' and \'.cart-buttons\' respectively. After these CSS selectors the banner is displayed.',
    'OSC_PAYPAL_BANNER_PAYMENTPAGESELECTOR'         => 'CSS selector of the "Pay" page (checkout step 3) after which the banner is displayed.',
    'HELP_OSC_PAYPAL_BANNER_PAYMENTPAGESELECTOR'    => 'Default values for Flow and Wave themes are: \'.checkoutSteps ~ .spacer\' and \'.checkout-steps\' respectively. After these CSS selectors the banner is displayed.',
    'OSC_PAYPAL_BANNER_COLORSCHEME'                 => 'Select installment banner\'s color',
    'OSC_PAYPAL_BANNER_COLORSCHEMEBLUE'             => 'blue',
    'OSC_PAYPAL_BANNER_COLORSCHEMEBLACK'            => 'black',
    'OSC_PAYPAL_BANNER_COLORSCHEMEWHITE'            => 'white',
    'OSC_PAYPAL_BANNER_COLORSCHEMEWHITENOBORDER'    => 'white, no border',
    // <-- PSPAYPAL-491

    'OSC_PAYPAL_SUBSCRITION_PART_ARTICLE_TITLE'   => '%s (Partial delivery no. %s from %s)',
];
