[{assign var="oConfig" value=$oViewConf->getConfig()}]
    [{assign var="PayPalSDKJS" value=$oConfig->getGlobalParameter("PayPalSDKJS")}]
    [{if !$PayPalSDKJS}]
        [{capture assign="PayPalSDKJS"}]
            [{include file="@osc_paypal/frontend/shared/layout/base_js.tpl" commitFlow=$commitFlow}]
        [{/capture}]
    [{$oConfig->setGlobalParameter("PayPalSDKJS", $PayPalSDKJS)}]
    [{/if}]
[{if $oViewConf->isFlowCompatibleTheme()}]
    [{include file='@osc_paypal/frontend/flow/vaultedpaymentsources.tpl'}]
[{else}]
    [{include file='@osc_paypal/frontend/wave/vaultedpaymentsources.tpl'}]
[{/if}]