[{$smarty.block.parent}]
[{if $oViewConf->showPayPalCheckoutBannerOnSearchResultsPage()}]
    [{assign var="paypalInstallmentPrice" value=$oxcmp_basket->getBruttoSum()}]
    [{if $oxcmp_basket->isPriceViewModeNetto()}]
        [{assign var="paypalInstallmentPrice" value=$oxcmp_basket->getNettoSum()}]
    [{/if}]
    [{include file="@osc_paypal/frontend/shared/installment_banners.tpl" amount=$paypalInstallmentPrice selector=$oViewConf->getPayPalCheckoutBannerSearchPageSelector()}]
[{/if}]
