[{if $sPaymentID == "oscpaypal_express"}]
    [{include file='modules/osc/paypal/select_payment.tpl'}]
[{elseif $sPaymentID == "oscpaypal_sepa"}]
    [{assign var="config" value=$oViewConf->getPayPalCheckoutConfig()}]
    [{if $config->isActive() && !$oViewConf->isPayPalExpressSessionActive()}]
        [{if $oViewConf->isFlowCompatibleTheme()}]
            [{include file="modules/osc/paypal/sepa_flow.tpl"}]
        [{else}]
            [{include file="modules/osc/paypal/sepa_wave.tpl"}]
        [{/if}]
    [{/if}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]
