[{assign var="payment" value=$oView->getPayment()}]
[{if "oscpaypal_acdc" == $payment->getId() || "oscpaypal_pui" == $payment->getId() || $vaultedPaymentDescription}]
    [{assign var="oConfig" value=$oViewConf->getConfig()}]
    [{assign var="PayPalSDKJS" value=$oConfig->getGlobalParameter("PayPalSDKJS")}]
    [{if !$PayPalSDKJS}]
        [{capture assign="PayPalSDKJS"}]
            [{include file="modules/osc/paypal/base_js.tpl" commitFlow=false}]
        [{/capture}]
        [{$oConfig->setGlobalParameter("PayPalSDKJS", $PayPalSDKJS)}]
    [{/if}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{include file="modules/osc/paypal/shipping_and_payment_flow.tpl"}]
    [{else}]
        [{include file="modules/osc/paypal/shipping_and_payment_wave.tpl"}]
    [{/if}]
[{elseif "oscpaypal" == $payment->getId()}]
    [{if $oViewConf->isFlowCompatibleTheme()}]
        [{include file="modules/osc/paypal/shipping_and_payment_paypal_flow.tpl"}]
    [{else}]
        [{include file="modules/osc/paypal/shipping_and_payment_paypal_wave.tpl"}]
    [{/if}]
[{else}]
    [{$smarty.block.parent}]
[{/if}]